/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Do not edit these files manually.
 */
//

import { BungieClientProtocol } from './..';
import { BungieNetResponse } from '../interfaces/BungieNetResponse';
import { addParam } from '../util';
import { ApiUsage } from '../models/Applications/ApiUsage';
import { Application } from '../models/Applications/Application';

/**
 * Get API usage by application for time frame specified. You can go as far back as
 * 30 days ago, and can ask for up to a 48 hour window of time in a single request.
 * You must be authenticated with at least the ReadUserData permission to access
 * this endpoint.
 * @see {@link https://bungie-net.github.io/#App.GetApplicationApiUsage}
 */
export async function getApplicationApiUsage(
  client: BungieClientProtocol,
  params: {
    /** ID of the application to get usage statistics. */
    applicationId: number;
    /** End time for query. Goes to now if not specified. */
    end?: string;
    /** Start time for query. Goes to 24 hours ago if not specified. */
    start?: string;
  }
): Promise<BungieNetResponse<ApiUsage>> {
  const url = new URL(`https://www.bungie.net/Platform/App/ApiUsage/${params.applicationId}/`);
  addParam(url, params.end, 'end');
  addParam(url, params.start, 'start');
  return client.fetch({ method: 'GET', url });
}

/**
 * Get list of applications created by Bungie.
 * @see {@link https://bungie-net.github.io/#App.GetBungieApplications}
 */
export async function getBungieApplications(
  client: BungieClientProtocol
): Promise<BungieNetResponse<Application[]>> {
  const url = new URL(`https://www.bungie.net/Platform/App/FirstParty/`);
  return client.fetch({ method: 'GET', url });
}
