/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type ClanBanner
 * @see {@link https://bungie-net.github.io/#/components/schemas/GroupsV2.ClanBanner}
*/
class ClanBanner {
  /**
   * @readonly
   * @type number
  */
  decalId;
  /**
   * @readonly
   * @type number
  */
  decalColorId;
  /**
   * @readonly
   * @type number
  */
  decalBackgroundColorId;
  /**
   * @readonly
   * @type number
  */
  gonfalonId;
  /**
   * @readonly
   * @type number
  */
  gonfalonColorId;
  /**
   * @readonly
   * @type number
  */
  gonfalonDetailId;
  /**
   * @readonly
   * @type number
  */
  gonfalonDetailColorId;
}
module.exports = ClanBanner;
