/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type GroupMemberApplication
 * @property {string} groupId 
 * @property {string} creationDate 
 * @property {GroupApplicationResolveState} resolveState 
 * @property {string?} resolveDate 
 * @property {string?} resolvedByMembershipId 
 * @property {string} requestMessage 
 * @property {string} resolveMessage 
 * @property {GroupUserInfoCard} destinyUserInfo 
 * @property {UserInfoCard} bungieNetUserInfo 
 * @see {@link https://bungie-net.github.io/#/components/schemas/GroupsV2.GroupMemberApplication}
*/
class GroupMemberApplication {
  /** @readonly */
  groupId;
  /** @readonly */
  creationDate;
  /** @readonly */
  resolveState;
  /** @readonly */
  resolveDate;
  /** @readonly */
  resolvedByMembershipId;
  /** @readonly */
  requestMessage;
  /** @readonly */
  resolveMessage;
  /** @readonly */
  destinyUserInfo;
  /** @readonly */
  bungieNetUserInfo;
}
module.exports = GroupMemberApplication;
