/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * A small infocard of group information, usually used for when a list of groups
 * are returned
 * @type GroupV2Card
 * @property {string} groupId 
 * @property {string} name 
 * @property {GroupType} groupType 
 * @property {string} creationDate 
 * @property {string} about 
 * @property {string} motto 
 * @property {number} memberCount 
 * @property {string} locale 
 * @property {MembershipOption} membershipOption 
 * @property {Capabilities} capabilities This enum represents a set of flags - use bitwise operators to check which of these match your value.
 * @property {GroupV2ClanInfo} clanInfo 
 * @property {string} avatarPath 
 * @property {string} theme 
 * @see {@link https://bungie-net.github.io/#/components/schemas/GroupsV2.GroupV2Card}
*/
class GroupV2Card {
  /** @readonly */
  groupId;
  /** @readonly */
  name;
  /** @readonly */
  groupType;
  /** @readonly */
  creationDate;
  /** @readonly */
  about;
  /** @readonly */
  motto;
  /** @readonly */
  memberCount;
  /** @readonly */
  locale;
  /** @readonly */
  membershipOption;
  /** @readonly */
  capabilities;
  /** @readonly */
  clanInfo;
  /** @readonly */
  avatarPath;
  /** @readonly */
  theme;
}
module.exports = GroupV2Card;
