/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
/** @see {@link https://bungie-net.github.io/#/components/schemas/GroupsV2.GroupEditAction} */
export interface GroupEditAction {
    readonly name: string;
    readonly about: string;
    readonly motto: string;
    readonly theme: string;
    readonly avatarImageIndex?: number;
    readonly tags: string;
    readonly isPublic?: boolean;
    readonly membershipOption?: number;
    readonly isPublicTopicAdminOnly?: boolean;
    readonly allowChat?: boolean;
    readonly chatSecurity?: number;
    readonly callsign: string;
    readonly locale: string;
    readonly homepage?: number;
    readonly enableInvitationMessagingForAdmins?: boolean;
    readonly defaultPublicity?: number;
}
