/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * The same as GroupV2ClanInfo, but includes any investment data.
 * @type GroupV2ClanInfoAndInvestment
 * @property {Object.key<number, DestinyProgression>} d2ClanProgressions 
 * @property {string} clanCallsign 
 * @property {ClanBanner} clanBannerData 
 * @see {@link https://bungie-net.github.io/#/components/schemas/GroupsV2.GroupV2ClanInfoAndInvestment}
*/
class GroupV2ClanInfoAndInvestment {
  /** @readonly */
  d2ClanProgressions;
  /** @readonly */
  clanCallsign;
  /** @readonly */
  clanBannerData;
}
module.exports = GroupV2ClanInfoAndInvestment;
