/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/** @type GroupUserInfoCard */
exports.GroupUserInfoCard = require('./GroupUserInfoCard');
/** @type GroupResponse */
exports.GroupResponse = require('./GroupResponse');
/** @type GroupV2 */
exports.GroupV2 = require('./GroupV2');
exports.GroupType = require('./GroupType');
exports.ChatSecuritySetting = require('./ChatSecuritySetting');
exports.GroupHomepage = require('./GroupHomepage');
exports.MembershipOption = require('./MembershipOption');
exports.GroupPostPublicity = require('./GroupPostPublicity');
/** @type GroupFeatures */
exports.GroupFeatures = require('./GroupFeatures');
exports.Capabilities = require('./Capabilities');
exports.HostGuidedGamesPermissionLevel = require('./HostGuidedGamesPermissionLevel');
exports.RuntimeGroupMemberType = require('./RuntimeGroupMemberType');
/** @type GroupV2ClanInfoAndInvestment */
exports.GroupV2ClanInfoAndInvestment = require('./GroupV2ClanInfoAndInvestment');
/** @type ClanBanner */
exports.ClanBanner = require('./ClanBanner');
/** @type GroupMember */
exports.GroupMember = require('./GroupMember');
exports.GroupAllianceStatus = require('./GroupAllianceStatus');
/** @type GroupPotentialMember */
exports.GroupPotentialMember = require('./GroupPotentialMember');
exports.GroupPotentialMemberStatus = require('./GroupPotentialMemberStatus');
exports.GroupDateRange = require('./GroupDateRange');
/** @type GroupQuery */
exports.GroupQuery = require('./GroupQuery');
/** @type GroupNameSearchRequest */
exports.GroupNameSearchRequest = require('./GroupNameSearchRequest');
/** @type GroupEditAction */
exports.GroupEditAction = require('./GroupEditAction');
/** @type GroupOptionsEditAction */
exports.GroupOptionsEditAction = require('./GroupOptionsEditAction');
/** @type GroupOptionalConversationAddRequest */
exports.GroupOptionalConversationAddRequest = require('./GroupOptionalConversationAddRequest');
/** @type GroupOptionalConversationEditRequest */
exports.GroupOptionalConversationEditRequest = require('./GroupOptionalConversationEditRequest');
/** @type GroupBanRequest */
exports.GroupBanRequest = require('./GroupBanRequest');
/** @type GroupApplicationRequest */
exports.GroupApplicationRequest = require('./GroupApplicationRequest');
/** @type GroupApplicationListRequest */
exports.GroupApplicationListRequest = require('./GroupApplicationListRequest');
exports.GroupsForMemberFilter = require('./GroupsForMemberFilter');
/** @type GroupV2Card */
exports.GroupV2Card = require('./GroupV2Card');
/** @type GroupV2ClanInfo */
exports.GroupV2ClanInfo = require('./GroupV2ClanInfo');
exports.GroupSortBy = require('./GroupSortBy');
/** @type GroupSearchResponse */
exports.GroupSearchResponse = require('./GroupSearchResponse');
/** @type GroupOptionalConversation */
exports.GroupOptionalConversation = require('./GroupOptionalConversation');
/** @type GroupMemberLeaveResult */
exports.GroupMemberLeaveResult = require('./GroupMemberLeaveResult');
/** @type GroupBan */
exports.GroupBan = require('./GroupBan');
/** @type GroupMemberApplication */
exports.GroupMemberApplication = require('./GroupMemberApplication');
exports.GroupApplicationResolveState = require('./GroupApplicationResolveState');
/** @type GetGroupsForMemberResponse */
exports.GetGroupsForMemberResponse = require('./GetGroupsForMemberResponse');
/** @type GroupMembership */
exports.GroupMembership = require('./GroupMembership');
/** @type GroupMembershipSearchResponse */
exports.GroupMembershipSearchResponse = require('./GroupMembershipSearchResponse');
/** @type GroupPotentialMembershipSearchResponse */
exports.GroupPotentialMembershipSearchResponse = require('./GroupPotentialMembershipSearchResponse');
/** @type GroupPotentialMembership */
exports.GroupPotentialMembership = require('./GroupPotentialMembership');
/** @type GroupApplicationResponse */
exports.GroupApplicationResponse = require('./GroupApplicationResponse');
