/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof ContentTypeProperty}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Content.Models.ContentTypeProperty}
*/
module.exports = class ContentTypeProperty {
  /**
   * @readonly
   * @type {string}
  */
  name;
  /**
   * @readonly
   * @type {string}
  */
  rootPropertyName;
  /**
   * @readonly
   * @type {string}
  */
  readableName;
  /**
   * @readonly
   * @type {string}
  */
  value;
  /**
   * @readonly
   * @type {string}
  */
  propertyDescription;
  /**
   * @readonly
   * @type {boolean}
  */
  localizable;
  /**
   * @readonly
   * @type {boolean}
  */
  fallback;
  /**
   * @readonly
   * @type {boolean}
  */
  enabled;
  /**
   * @readonly
   * @type {number}
  */
  order;
  /**
   * @readonly
   * @type {boolean}
  */
  visible;
  /**
   * @readonly
   * @type {boolean}
  */
  isTitle;
  /**
   * @readonly
   * @type {boolean}
  */
  required;
  /**
   * @readonly
   * @type {number}
  */
  maxLength;
  /**
   * @readonly
   * @type {number}
  */
  maxByteLength;
  /**
   * @readonly
   * @type {number}
  */
  maxFileSize;
  /**
   * @readonly
   * @type {string}
  */
  regexp;
  /**
   * @readonly
   * @type {string}
  */
  validateAs;
  /**
   * @readonly
   * @type {string}
  */
  rssAttribute;
  /**
   * @readonly
   * @type {string}
  */
  visibleDependency;
  /**
   * @readonly
   * @type {string}
  */
  visibleOn;
  /**
   * @readonly
   * @type {import('./ContentPropertyDataTypeEnum')}
  */
  datatype;
  /**
   * @readonly
   * @type {{{[key: string]: string}}}
  */
  attributes;
  /**
   * @readonly
   * @type {ContentTypeProperty[]}
  */
  childProperties;
  /**
   * @readonly
   * @type {string}
  */
  contentTypeAllowed;
  /**
   * @readonly
   * @type {string}
  */
  bindToProperty;
  /**
   * @readonly
   * @type {string}
  */
  boundRegex;
  /**
   * @readonly
   * @type {{{[key: string]: string}}}
  */
  representationSelection;
  /**
   * @readonly
   * @type {import('./ContentTypeDefaultValue')[]}
  */
  defaultValues;
  /**
   * @readonly
   * @type {boolean}
  */
  isExternalAllowed;
  /**
   * @readonly
   * @type {string}
  */
  propertySection;
  /**
   * @readonly
   * @type {number}
  */
  weight;
  /**
   * @readonly
   * @type {string}
  */
  entitytype;
  /**
   * @readonly
   * @type {boolean}
  */
  isCombo;
  /**
   * @readonly
   * @type {boolean}
  */
  suppressProperty;
  /**
   * @readonly
   * @type {string[]}
  */
  legalContentTypes;
  /**
   * @readonly
   * @type {string}
  */
  representationValidationString;
  /**
   * @readonly
   * @type {number}
  */
  minWidth;
  /**
   * @readonly
   * @type {number}
  */
  maxWidth;
  /**
   * @readonly
   * @type {number}
  */
  minHeight;
  /**
   * @readonly
   * @type {number}
  */
  maxHeight;
  /**
   * @readonly
   * @type {boolean}
  */
  isVideo;
  /**
   * @readonly
   * @type {boolean}
  */
  isImage;
}
