/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type ContentTypeProperty
 * @property {string} name 
 * @property {string} rootPropertyName 
 * @property {string} readableName 
 * @property {string} value 
 * @property {string} propertyDescription 
 * @property {boolean} localizable 
 * @property {boolean} fallback 
 * @property {boolean} enabled 
 * @property {number} order 
 * @property {boolean} visible 
 * @property {boolean} isTitle 
 * @property {boolean} required 
 * @property {number} maxLength 
 * @property {number} maxByteLength 
 * @property {number} maxFileSize 
 * @property {string} regexp 
 * @property {string} validateAs 
 * @property {string} rssAttribute 
 * @property {string} visibleDependency 
 * @property {string} visibleOn 
 * @property {ContentPropertyDataTypeEnum} datatype 
 * @property {Object.key<string, string>} attributes 
 * @property {ContentTypeProperty[]} childProperties 
 * @property {string} contentTypeAllowed 
 * @property {string} bindToProperty 
 * @property {string} boundRegex 
 * @property {Object.key<string, string>} representationSelection 
 * @property {ContentTypeDefaultValue[]} defaultValues 
 * @property {boolean} isExternalAllowed 
 * @property {string} propertySection 
 * @property {number} weight 
 * @property {string} entitytype 
 * @property {boolean} isCombo 
 * @property {boolean} suppressProperty 
 * @property {string[]} legalContentTypes 
 * @property {string} representationValidationString 
 * @property {number} minWidth 
 * @property {number} maxWidth 
 * @property {number} minHeight 
 * @property {number} maxHeight 
 * @property {boolean} isVideo 
 * @property {boolean} isImage 
 * @see {@link https://bungie-net.github.io/#/components/schemas/Content.Models.ContentTypeProperty}
*/
class ContentTypeProperty {
  /** @readonly */
  name;
  /** @readonly */
  rootPropertyName;
  /** @readonly */
  readableName;
  /** @readonly */
  value;
  /** @readonly */
  propertyDescription;
  /** @readonly */
  localizable;
  /** @readonly */
  fallback;
  /** @readonly */
  enabled;
  /** @readonly */
  order;
  /** @readonly */
  visible;
  /** @readonly */
  isTitle;
  /** @readonly */
  required;
  /** @readonly */
  maxLength;
  /** @readonly */
  maxByteLength;
  /** @readonly */
  maxFileSize;
  /** @readonly */
  regexp;
  /** @readonly */
  validateAs;
  /** @readonly */
  rssAttribute;
  /** @readonly */
  visibleDependency;
  /** @readonly */
  visibleOn;
  /** @readonly */
  datatype;
  /** @readonly */
  attributes;
  /** @readonly */
  childProperties;
  /** @readonly */
  contentTypeAllowed;
  /** @readonly */
  bindToProperty;
  /** @readonly */
  boundRegex;
  /** @readonly */
  representationSelection;
  /** @readonly */
  defaultValues;
  /** @readonly */
  isExternalAllowed;
  /** @readonly */
  propertySection;
  /** @readonly */
  weight;
  /** @readonly */
  entitytype;
  /** @readonly */
  isCombo;
  /** @readonly */
  suppressProperty;
  /** @readonly */
  legalContentTypes;
  /** @readonly */
  representationValidationString;
  /** @readonly */
  minWidth;
  /** @readonly */
  maxWidth;
  /** @readonly */
  minHeight;
  /** @readonly */
  maxHeight;
  /** @readonly */
  isVideo;
  /** @readonly */
  isImage;
}
module.exports = ContentTypeProperty;
