/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type UserRewardAvailabilityModel
 * @property {RewardAvailabilityModel} AvailabilityModel 
 * @property {boolean} IsAvailableForUser 
 * @property {boolean} IsUnlockedForUser 
 * @see {@link https://bungie-net.github.io/#/components/schemas/Tokens.UserRewardAvailabilityModel}
*/
class UserRewardAvailabilityModel {
  /** @readonly */
  AvailabilityModel;
  /** @readonly */
  IsAvailableForUser;
  /** @readonly */
  IsUnlockedForUser;
}
module.exports = UserRewardAvailabilityModel;
