/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Do not edit these files manually.
 */
//

import { DestinyFireteamFinderLobbyPrivacyScope } from './DestinyFireteamFinderLobbyPrivacyScope';
import { DestinyFireteamFinderListingValue } from './DestinyFireteamFinderListingValue';

/** @see {@link https://bungie-net.github.io/#/components/schemas/FireteamFinder.DestinyFireteamFinderLobbySettings} */

export interface DestinyFireteamFinderLobbySettings {
  readonly maxPlayerCount: number;
  readonly onlinePlayersOnly: boolean;
  readonly privacyScope: DestinyFireteamFinderLobbyPrivacyScope;
  readonly scheduledDateTime: string;
  readonly clanId: string;
  readonly listingValues: DestinyFireteamFinderListingValue[];
  /** Mapped to DestinyFireteamFinderActivityGraphDefinition in the manifest. */
  readonly activityGraphHash: number;
  /** Mapped to DestinyActivityDefinition in the manifest. */
  readonly activityHash: number;
}
