/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/** @type DestinyRecordDefinition */
exports.DestinyRecordDefinition = require('./DestinyRecordDefinition');
/** @type DestinyRecordTitleBlock */
exports.DestinyRecordTitleBlock = require('./DestinyRecordTitleBlock');
/** @type DestinyRecordCompletionBlock */
exports.DestinyRecordCompletionBlock = require('./DestinyRecordCompletionBlock');
/** @type SchemaRecordStateBlock */
exports.SchemaRecordStateBlock = require('./SchemaRecordStateBlock');
/** @type DestinyRecordExpirationBlock */
exports.DestinyRecordExpirationBlock = require('./DestinyRecordExpirationBlock');
/** @type DestinyRecordIntervalBlock */
exports.DestinyRecordIntervalBlock = require('./DestinyRecordIntervalBlock');
/** @type DestinyRecordIntervalObjective */
exports.DestinyRecordIntervalObjective = require('./DestinyRecordIntervalObjective');
/** @type DestinyRecordIntervalRewards */
exports.DestinyRecordIntervalRewards = require('./DestinyRecordIntervalRewards');
