/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//

import { BungieClientProtocol } from '../../client';
import { BungieNetResponse } from '../../interfaces/BungieNetResponse';

/**
 * Declines a friend relationship with the target user. The user must be on your
 * incoming friend request list, though no error will occur if they are not.
 * @see {@link https://bungie-net.github.io/#Social.DeclineFriendRequest}
 */
export async function declineFriendRequest(
  params: {
    /** The membership id of the user you wish to decline. */
    membershipId: string;
  },
  client: BungieClientProtocol
): Promise<BungieNetResponse<unknown>> {
  const url = new URL(
    `https://www.bungie.net/Platform/Social/Friends/Requests/Decline/${params.membershipId}/`
  );

  return client.fetch({ method: 'POST', url });
}
