/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * Items can have Energy Capacity, and plugs can provide that capacity such as on a
 * piece of Armor in Armor 2.0. This is how much "Energy" can be spent on
 * activating plugs for this item.
 * @type DestinyEnergyCapacityEntry
 * @property {number} capacityValue How much energy capacity this plug provides.
 * @property {number} energyTypeHash Energy provided by a plug is always of a specific type - this is the hash identifier for the energy type for which it provides Capacity. Mapped to DestinyEnergyTypeDefinition in the manifest.
 * @property {DestinyEnergyType} energyType The Energy Type for this energy capacity, in enum form for easy use.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Items.DestinyEnergyCapacityEntry}
*/
class DestinyEnergyCapacityEntry {
  /** @readonly */
  capacityValue;
  /** @readonly */
  energyTypeHash;
  /** @readonly */
  energyType;
}
module.exports = DestinyEnergyCapacityEntry;
