/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
/**
 * This is a reference to, and summary data for, a specific item that you can get
 * as a result of Using or Acquiring some other Item (For example, this could be
 * summary information for an Emote that you can get by opening an an Eververse Box)
 * See DestinyDerivedItemCategoryDefinition for more information.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Items.DestinyDerivedItemDefinition}
*/
export interface DestinyDerivedItemDefinition {
    /**
     * The hash for the DestinyInventoryItemDefinition of this derived item, if there
     * is one. Sometimes we are given this information as a manual override, in which
     * case there won't be an actual DestinyInventoryItemDefinition for what we display,
     * but you can still show the strings from this object itself.
    */
    readonly itemHash?: number;
    /** The name of the derived item. */
    readonly itemName: string;
    /** Additional details about the derived item, in addition to the description. */
    readonly itemDetail: string;
    /** A brief description of the item. */
    readonly itemDescription: string;
    /** An icon for the item. */
    readonly iconPath: string;
    /**
     * If the item was derived from a "Preview Vendor", this will be an index into the
     * DestinyVendorDefinition's itemList property. Otherwise, -1.
    */
    readonly vendorItemIndex: number;
}
