/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/** @type DestinyItemTierTypeDefinition */
exports.DestinyItemTierTypeDefinition = require('./DestinyItemTierTypeDefinition');
/** @type DestinyItemTierTypeInfusionBlock */
exports.DestinyItemTierTypeInfusionBlock = require('./DestinyItemTierTypeInfusionBlock');
/** @type DestinyDerivedItemCategoryDefinition */
exports.DestinyDerivedItemCategoryDefinition = require('./DestinyDerivedItemCategoryDefinition');
/** @type DestinyDerivedItemDefinition */
exports.DestinyDerivedItemDefinition = require('./DestinyDerivedItemDefinition');
/** @type DestinyItemPlugDefinition */
exports.DestinyItemPlugDefinition = require('./DestinyItemPlugDefinition');
/** @type DestinyPlugRuleDefinition */
exports.DestinyPlugRuleDefinition = require('./DestinyPlugRuleDefinition');
/** @type DestinyParentItemOverride */
exports.DestinyParentItemOverride = require('./DestinyParentItemOverride');
/** @type DestinyEnergyCapacityEntry */
exports.DestinyEnergyCapacityEntry = require('./DestinyEnergyCapacityEntry');
/** @type DestinyEnergyCostEntry */
exports.DestinyEnergyCostEntry = require('./DestinyEnergyCostEntry');
