/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetCollectibleNodeDetailsParams
 * @property {string} characterId The Destiny Character ID of the character for whom we're getting collectible detail info.
 * @property {number} collectiblePresentationNodeHash The hash identifier of the Presentation Node for whom we should return collectible details. Details will only be returned for collectibles that are direct descendants of this node.
 * @property {DestinyComponentType[]} components A comma separated list of components to return (as strings or numeric values). See the DestinyComponentType enum for valid components to request. You must request at least one component to receive results.
 * @property {string} destinyMembershipId Destiny membership ID of another user. You may be denied.
 * @property {BungieMembershipType} membershipType A valid non-BungieNet membership type.
 * @see {@link https://bungie-net.github.io/#Destiny2.GetCollectibleNodeDetails}
*/

/**
 * Given a Presentation Node that has Collectibles as direct descendants, this will
 * return item details about those descendants in the context of the requesting
 * character.
 * @param {GetCollectibleNodeDetailsParams} params
 * @returns Promise<BungieNetResponse<DestinyCollectibleNodeDetailResponse>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#Destiny2.GetCollectibleNodeDetails}
*/
module.exports = async function getCollectibleNodeDetails(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/Destiny2/${params.membershipType}/Profile/${params.destinyMembershipId}/Character/${params.characterId}/Collectibles/${params.collectiblePresentationNodeHash}/`,
    params: {
      components: params.components ? params.components.join(',') : undefined
    }
  });
}
