/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetLeaderboardsParams
 * @property {string} destinyMembershipId The Destiny membershipId of the user to retrieve.
 * @property {number?} maxtop Maximum number of top players to return. Use a large number to get entire leaderboard.
 * @property {BungieMembershipType} membershipType A valid non-BungieNet membership type.
 * @property {string?} modes List of game modes for which to get leaderboards. See the documentation for DestinyActivityModeType for valid values, and pass in string representation, comma delimited.
 * @property {string?} statid ID of stat to return rather than returning all Leaderboard stats.
 * @see {@link https://bungie-net.github.io/#Destiny2.GetLeaderboards}
*/

/**
 * Gets leaderboards with the signed in user's friends and the supplied
 * destinyMembershipId as the focus. PREVIEW: This endpoint has not yet been
 * implemented. It is being returned for a preview of future functionality, and for
 * public comment/suggestion/preparation.
 * @param {GetLeaderboardsParams} params
 * @returns Promise<BungieNetResponse<DestinyLeaderboardResults>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#Destiny2.GetLeaderboards}
*/
module.exports = async function getLeaderboards(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/Destiny2/${params.membershipType}/Account/${params.destinyMembershipId}/Stats/Leaderboards/`,
    params: {
      maxtop: params.maxtop,
      modes: params.modes,
      statid: params.statid
    }
  });
}
