/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyRecordComponent
 * @property {DestinyRecordState} state This enum represents a set of flags - use bitwise operators to check which of these match your value.
 * @property {DestinyObjectiveProgress[]} objectives 
 * @property {DestinyObjectiveProgress[]} intervalObjectives 
 * @property {number} intervalsRedeemedCount 
 * @property {number?} completedCount If available, this is the number of times this record has been completed. For example, the number of times a seal title has been gilded.
 * @property {boolean[]} rewardVisibilty If available, a list that describes which reward rewards should be shown (true) or hidden (false). This property is for regular record rewards, and not for interval objective rewards.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Components.Records.DestinyRecordComponent}
*/
class DestinyRecordComponent {
  /** @readonly */
  state;
  /** @readonly */
  objectives;
  /** @readonly */
  intervalObjectives;
  /** @readonly */
  intervalsRedeemedCount;
  /** @readonly */
  completedCount;
  /** @readonly */
  rewardVisibilty;
}
module.exports = DestinyRecordComponent;
