/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyCharacterRecordsComponent
 * @property {number[]} featuredRecordHashes Mapped to DestinyRecordDefinition in the manifest.
 * @property {Object.key<number, DestinyRecordComponent>} records 
 * @property {number} recordCategoriesRootNodeHash The hash for the root presentation node definition of Triumph categories. Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {number} recordSealsRootNodeHash The hash for the root presentation node definition of Triumph Seals. Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Components.Records.DestinyCharacterRecordsComponent}
*/
class DestinyCharacterRecordsComponent {
  /** @readonly */
  featuredRecordHashes;
  /** @readonly */
  records;
  /** @readonly */
  recordCategoriesRootNodeHash;
  /** @readonly */
  recordSealsRootNodeHash;
}
module.exports = DestinyCharacterRecordsComponent;
