/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
import { BungieNetResponse } from '../../interfaces/server-response';
import { AccessTokenObject } from '../../client';
import { BungieRewardDisplay } from '../../models';
/** @see {@link https://bungie-net.github.io/#Tokens.GetBungieRewardsForUser} */
export type GetBungieRewardsForUserParams = {
    /**
     * bungie.net user membershipId for requested user rewards. If not self, elevated
     * permissions are required.
    */
    membershipId: string;
};
/**
 * Returns the bungie rewards for the targeted user.
 * @see {@link https://bungie-net.github.io/#Tokens.GetBungieRewardsForUser}
*/
export declare function getBungieRewardsForUser(this: AccessTokenObject | void, params: GetBungieRewardsForUserParams): Promise<BungieNetResponse<{
    [key: string]: BungieRewardDisplay;
}>>;
