/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetPartnerOfferSkuHistoryParams
 * @property {number} partnerApplicationId The partner application identifier.
 * @property {string} targetBnetMembershipId The bungie.net user to apply missing offers to. If not self, elevated permissions are required.
 * @see {@link https://bungie-net.github.io/#Tokens.GetPartnerOfferSkuHistory}
*/

/**
 * Returns the partner sku and offer history of the targeted user. Elevated
 * permissions are required to see users that are not yourself.
 * @param {GetPartnerOfferSkuHistoryParams} params
 * @returns Promise<BungieNetResponse<CEListOfPartnerOfferSkuHistoryResponse>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#Tokens.GetPartnerOfferSkuHistory}
*/
module.exports = async function getPartnerOfferSkuHistory(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/Tokens/Partner/History/${params.partnerApplicationId}/${params.targetBnetMembershipId}/`
  });
}
