/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * Localized text relevant to a given EMail setting in a given localization. Extra
 * settings specifically for subscriptions.
 * @type EMailSettingSubscriptionLocalization
 * @property {string} unknownUserDescription 
 * @property {string} registeredUserDescription 
 * @property {string} unregisteredUserDescription 
 * @property {string} unknownUserActionText 
 * @property {string} knownUserActionText 
 * @property {string} title 
 * @property {string} description 
 * @see {@link https://bungie-net.github.io/#/components/schemas/User.EMailSettingSubscriptionLocalization}
*/
class EMailSettingSubscriptionLocalization {
  /** @readonly */
  unknownUserDescription;
  /** @readonly */
  registeredUserDescription;
  /** @readonly */
  unregisteredUserDescription;
  /** @readonly */
  unknownUserActionText;
  /** @readonly */
  knownUserActionText;
  /** @readonly */
  title;
  /** @readonly */
  description;
}
module.exports = EMailSettingSubscriptionLocalization;
