/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type EmailViewDefinitionSetting
 * @property {string} name The identifier for this UI Setting, which can be used to relate it to custom strings or other data as desired.
 * @property {Object.key<string, EMailSettingLocalization>} localization A dictionary of localized text for the EMail setting, keyed by the locale.
 * @property {boolean} setByDefault If true, this setting should be set by default if the user hasn't chosen whether it's set or cleared yet.
 * @property {OptInFlags} optInAggregateValue The OptInFlags value to set or clear if this setting is set or cleared in the UI. It is the aggregate of all underlying opt-in flags related to this setting. This enum represents a set of flags - use bitwise operators to check which of these match your value.
 * @property {EmailSubscriptionDefinition[]} subscriptions The subscriptions to show as children of this setting, if any.
 * @see {@link https://bungie-net.github.io/#/components/schemas/User.EmailViewDefinitionSetting}
*/
class EmailViewDefinitionSetting {
  /** @readonly */
  name;
  /** @readonly */
  localization;
  /** @readonly */
  setByDefault;
  /** @readonly */
  optInAggregateValue;
  /** @readonly */
  subscriptions;
}
module.exports = EmailViewDefinitionSetting;
