/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.7
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 * @see {@link https://bungie-net.github.io/#/components/schemas/User.OptInFlags}
*/
export var OptInFlags;
(function (OptInFlags) {
    OptInFlags[OptInFlags["None"] = 0] = "None";
    OptInFlags[OptInFlags["Newsletter"] = 1] = "Newsletter";
    OptInFlags[OptInFlags["System"] = 2] = "System";
    OptInFlags[OptInFlags["Marketing"] = 4] = "Marketing";
    OptInFlags[OptInFlags["UserResearch"] = 8] = "UserResearch";
    OptInFlags[OptInFlags["CustomerService"] = 16] = "CustomerService";
    OptInFlags[OptInFlags["Social"] = 32] = "Social";
    OptInFlags[OptInFlags["PlayTests"] = 64] = "PlayTests";
    OptInFlags[OptInFlags["PlayTestsLocal"] = 128] = "PlayTestsLocal";
    OptInFlags[OptInFlags["Careers"] = 256] = "Careers";
})(OptInFlags || (OptInFlags = {}));
