/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef ApprovePendingParams
 * @property {string} groupId ID of the group.
 * @property {string} membershipId The membership id being approved.
 * @property {BungieMembershipType} membershipType Membership type of the supplied membership ID.
 * @see {@link https://bungie-net.github.io/#GroupV2.ApprovePending}
*/

/**
 * Approve the given membershipId to join the group/clan as long as they have
 * applied.
 * @param {ApprovePendingParams} params
 * @returns Promise<boolean>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#GroupV2.ApprovePending}
*/
module.exports = async function approvePending(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: `https://www.bungie.net/Platform/GroupV2/${params.groupId}/Members/Approve/${params.membershipType}/${params.membershipId}/`,
    body
  });
}
