/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef DenyPendingForListParams
 * @property {string} groupId ID of the group.
 * @see {@link https://bungie-net.github.io/#GroupV2.DenyPendingForList}
*/

/**
 * Deny all of the pending users for the given group that match the passed-in .
 * @param {DenyPendingForListParams} params
 * @returns ListOfEntityActionResult
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#GroupV2.DenyPendingForList}
*/
module.exports = async function denyPendingForList(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: `https://www.bungie.net/Platform/GroupV2/${params.groupId}/Members/DenyList/`,
    body
  });
}
