/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef EditOptionalConversationParams
 * @property {string} conversationId Conversation Id of the channel being edited.
 * @property {string} groupId Group ID of the group to edit.
 * @see {@link https://bungie-net.github.io/#GroupV2.EditOptionalConversation}
*/

/**
 * Edit the settings of an optional conversation/chat channel. Requires admin
 * permissions to the group.
 * @param {EditOptionalConversationParams} params
 * @returns Promise<BungieNetResponse<int64>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#GroupV2.EditOptionalConversation}
*/
module.exports = async function editOptionalConversation(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: `https://www.bungie.net/Platform/GroupV2/${params.groupId}/OptionalConversations/Edit/${params.conversationId}/`,
    body
  });
}
