/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
import { BungieNetResponse } from '../../interfaces/server-response';
import { AccessTokenObject } from '../../client';
import { BungieMembershipType } from '../../models';
import { RuntimeGroupMemberType } from '../../models';
/** @see {@link https://bungie-net.github.io/#GroupV2.EditGroupMembership} */
export type EditGroupMembershipParams = {
    /** ID of the group to which the member belongs. */
    groupId: string;
    /** Membership ID to modify. */
    membershipId: string;
    /** Membership type of the provide membership ID. */
    membershipType: BungieMembershipType;
    /** New membertype for the specified member. */
    memberType: RuntimeGroupMemberType;
};
/**
 * Edit the membership type of a given member. You must have suitable permissions
 * in the group to perform this operation.
 * @see {@link https://bungie-net.github.io/#GroupV2.EditGroupMembership}
*/
export declare function editGroupMembership(this: AccessTokenObject | void, params: EditGroupMembershipParams): Promise<BungieNetResponse<number>>;
