/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * Get information about a specific group with the given name and type. The POST
 * version.
 * @returns Promise<BungieNetResponse<GroupResponse>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#GroupV2.GetGroupByNameV2}
*/
module.exports = async function getGroupByNameV2() {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: 'https://www.bungie.net/Platform/GroupV2/NameV2/',
    body
  });
}
