/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
import { BungieNetResponse } from '../../util/server-response.js';
import { BungieClient } from '../../util/client.js';
import { BungieMembershipType } from '../../schemas/index.js';
/** @see {@link https://bungie-net.github.io/#GroupV2.GetUserClanInviteSetting} */
export declare type GetUserClanInviteSettingParams = {
    /** The Destiny membership type of the account we wish to access settings. */
    mType: BungieMembershipType;
};
/**
 * Gets the state of the user's clan invite preferences for a particular membership
 * type - true if they wish to be invited to clans, false otherwise.
 * @see {@link https://bungie-net.github.io/#GroupV2.GetUserClanInviteSetting}
*/
export declare function GetUserClanInviteSetting(this: BungieClient, params: GetUserClanInviteSettingParams): Promise<BungieNetResponse<boolean>>;
