"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.individualGroupInviteCancel = exports.individualGroupInvite = exports.getPotentialGroupsForMember = exports.recoverGroupForFounder = exports.getGroupsForMember = exports.denyPendingForList = exports.approvePending = exports.approvePendingForList = exports.denyAllPending = exports.approveAllPending = exports.getInvitedIndividuals = exports.getPendingMemberships = exports.abdicateFoundership = exports.getBannedMembersOfGroup = exports.unbanMember = exports.banMember = exports.kickMember = exports.editGroupMembership = exports.getAdminsAndFounderOfGroup = exports.getMembersOfGroup = exports.editOptionalConversation = exports.addOptionalConversation = exports.editFounderOptions = exports.editClanBanner = exports.editGroup = exports.getGroupOptionalConversations = exports.getGroupByNameV2 = exports.getGroupByName = exports.getGroup = exports.groupSearch = exports.getRecommendedGroups = exports.getUserClanInviteSetting = exports.getAvailableThemes = exports.getAvailableAvatars = void 0;
var GetAvailableAvatars_1 = require("./GetAvailableAvatars");
Object.defineProperty(exports, "getAvailableAvatars", { enumerable: true, get: function () { return GetAvailableAvatars_1.getAvailableAvatars; } });
var GetAvailableThemes_1 = require("./GetAvailableThemes");
Object.defineProperty(exports, "getAvailableThemes", { enumerable: true, get: function () { return GetAvailableThemes_1.getAvailableThemes; } });
var GetUserClanInviteSetting_1 = require("./GetUserClanInviteSetting");
Object.defineProperty(exports, "getUserClanInviteSetting", { enumerable: true, get: function () { return GetUserClanInviteSetting_1.getUserClanInviteSetting; } });
var GetRecommendedGroups_1 = require("./GetRecommendedGroups");
Object.defineProperty(exports, "getRecommendedGroups", { enumerable: true, get: function () { return GetRecommendedGroups_1.getRecommendedGroups; } });
var GroupSearch_1 = require("./GroupSearch");
Object.defineProperty(exports, "groupSearch", { enumerable: true, get: function () { return GroupSearch_1.groupSearch; } });
var GetGroup_1 = require("./GetGroup");
Object.defineProperty(exports, "getGroup", { enumerable: true, get: function () { return GetGroup_1.getGroup; } });
var GetGroupByName_1 = require("./GetGroupByName");
Object.defineProperty(exports, "getGroupByName", { enumerable: true, get: function () { return GetGroupByName_1.getGroupByName; } });
var GetGroupByNameV2_1 = require("./GetGroupByNameV2");
Object.defineProperty(exports, "getGroupByNameV2", { enumerable: true, get: function () { return GetGroupByNameV2_1.getGroupByNameV2; } });
var GetGroupOptionalConversations_1 = require("./GetGroupOptionalConversations");
Object.defineProperty(exports, "getGroupOptionalConversations", { enumerable: true, get: function () { return GetGroupOptionalConversations_1.getGroupOptionalConversations; } });
var EditGroup_1 = require("./EditGroup");
Object.defineProperty(exports, "editGroup", { enumerable: true, get: function () { return EditGroup_1.editGroup; } });
var EditClanBanner_1 = require("./EditClanBanner");
Object.defineProperty(exports, "editClanBanner", { enumerable: true, get: function () { return EditClanBanner_1.editClanBanner; } });
var EditFounderOptions_1 = require("./EditFounderOptions");
Object.defineProperty(exports, "editFounderOptions", { enumerable: true, get: function () { return EditFounderOptions_1.editFounderOptions; } });
var AddOptionalConversation_1 = require("./AddOptionalConversation");
Object.defineProperty(exports, "addOptionalConversation", { enumerable: true, get: function () { return AddOptionalConversation_1.addOptionalConversation; } });
var EditOptionalConversation_1 = require("./EditOptionalConversation");
Object.defineProperty(exports, "editOptionalConversation", { enumerable: true, get: function () { return EditOptionalConversation_1.editOptionalConversation; } });
var GetMembersOfGroup_1 = require("./GetMembersOfGroup");
Object.defineProperty(exports, "getMembersOfGroup", { enumerable: true, get: function () { return GetMembersOfGroup_1.getMembersOfGroup; } });
var GetAdminsAndFounderOfGroup_1 = require("./GetAdminsAndFounderOfGroup");
Object.defineProperty(exports, "getAdminsAndFounderOfGroup", { enumerable: true, get: function () { return GetAdminsAndFounderOfGroup_1.getAdminsAndFounderOfGroup; } });
var EditGroupMembership_1 = require("./EditGroupMembership");
Object.defineProperty(exports, "editGroupMembership", { enumerable: true, get: function () { return EditGroupMembership_1.editGroupMembership; } });
var KickMember_1 = require("./KickMember");
Object.defineProperty(exports, "kickMember", { enumerable: true, get: function () { return KickMember_1.kickMember; } });
var BanMember_1 = require("./BanMember");
Object.defineProperty(exports, "banMember", { enumerable: true, get: function () { return BanMember_1.banMember; } });
var UnbanMember_1 = require("./UnbanMember");
Object.defineProperty(exports, "unbanMember", { enumerable: true, get: function () { return UnbanMember_1.unbanMember; } });
var GetBannedMembersOfGroup_1 = require("./GetBannedMembersOfGroup");
Object.defineProperty(exports, "getBannedMembersOfGroup", { enumerable: true, get: function () { return GetBannedMembersOfGroup_1.getBannedMembersOfGroup; } });
var AbdicateFoundership_1 = require("./AbdicateFoundership");
Object.defineProperty(exports, "abdicateFoundership", { enumerable: true, get: function () { return AbdicateFoundership_1.abdicateFoundership; } });
var GetPendingMemberships_1 = require("./GetPendingMemberships");
Object.defineProperty(exports, "getPendingMemberships", { enumerable: true, get: function () { return GetPendingMemberships_1.getPendingMemberships; } });
var GetInvitedIndividuals_1 = require("./GetInvitedIndividuals");
Object.defineProperty(exports, "getInvitedIndividuals", { enumerable: true, get: function () { return GetInvitedIndividuals_1.getInvitedIndividuals; } });
var ApproveAllPending_1 = require("./ApproveAllPending");
Object.defineProperty(exports, "approveAllPending", { enumerable: true, get: function () { return ApproveAllPending_1.approveAllPending; } });
var DenyAllPending_1 = require("./DenyAllPending");
Object.defineProperty(exports, "denyAllPending", { enumerable: true, get: function () { return DenyAllPending_1.denyAllPending; } });
var ApprovePendingForList_1 = require("./ApprovePendingForList");
Object.defineProperty(exports, "approvePendingForList", { enumerable: true, get: function () { return ApprovePendingForList_1.approvePendingForList; } });
var ApprovePending_1 = require("./ApprovePending");
Object.defineProperty(exports, "approvePending", { enumerable: true, get: function () { return ApprovePending_1.approvePending; } });
var DenyPendingForList_1 = require("./DenyPendingForList");
Object.defineProperty(exports, "denyPendingForList", { enumerable: true, get: function () { return DenyPendingForList_1.denyPendingForList; } });
var GetGroupsForMember_1 = require("./GetGroupsForMember");
Object.defineProperty(exports, "getGroupsForMember", { enumerable: true, get: function () { return GetGroupsForMember_1.getGroupsForMember; } });
var RecoverGroupForFounder_1 = require("./RecoverGroupForFounder");
Object.defineProperty(exports, "recoverGroupForFounder", { enumerable: true, get: function () { return RecoverGroupForFounder_1.recoverGroupForFounder; } });
var GetPotentialGroupsForMember_1 = require("./GetPotentialGroupsForMember");
Object.defineProperty(exports, "getPotentialGroupsForMember", { enumerable: true, get: function () { return GetPotentialGroupsForMember_1.getPotentialGroupsForMember; } });
var IndividualGroupInvite_1 = require("./IndividualGroupInvite");
Object.defineProperty(exports, "individualGroupInvite", { enumerable: true, get: function () { return IndividualGroupInvite_1.individualGroupInvite; } });
var IndividualGroupInviteCancel_1 = require("./IndividualGroupInviteCancel");
Object.defineProperty(exports, "individualGroupInviteCancel", { enumerable: true, get: function () { return IndividualGroupInviteCancel_1.individualGroupInviteCancel; } });
