/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef IndividualGroupInviteCancelParams
 * @property {string} groupId ID of the group you would like to join.
 * @property {string} membershipId Membership id of the account being cancelled.
 * @property {BungieMembershipType} membershipType MembershipType of the account being cancelled.
 * @see {@link https://bungie-net.github.io/#GroupV2.IndividualGroupInviteCancel}
*/

/**
 * Cancels a pending invitation to join a group.
 * @param {IndividualGroupInviteCancelParams} params
 * @returns Promise<GroupApplicationResponse>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#GroupV2.IndividualGroupInviteCancel}
*/
module.exports = async function individualGroupInviteCancel(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: `https://www.bungie.net/Platform/GroupV2/${params.groupId}/Members/IndividualInviteCancel/${params.membershipType}/${params.membershipId}/`
  });
}
