"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.destinyManifestLanguages = exports.ManifestComponents = void 0;
let ManifestComponents = function (ManifestComponents) {
  ManifestComponents["DestinyProgressionDefinition"] = "DestinyProgressionDefinition";
  ManifestComponents["DestinyInventoryItemDefinition"] = "DestinyInventoryItemDefinition";
  ManifestComponents["DestinyCollectibleDefinition"] = "DestinyCollectibleDefinition";
  ManifestComponents["DestinyMaterialRequirementSetDefinition"] = "DestinyMaterialRequirementSetDefinition";
  ManifestComponents["DestinyPresentationNodeDefinition"] = "DestinyPresentationNodeDefinition";
  ManifestComponents["DestinyObjectiveDefinition"] = "DestinyObjectiveDefinition";
  ManifestComponents["DestinyLocationDefinition"] = "DestinyLocationDefinition";
  ManifestComponents["DestinyVendorDefinition"] = "DestinyVendorDefinition";
  ManifestComponents["DestinyFactionDefinition"] = "DestinyFactionDefinition";
  ManifestComponents["DestinyDestinationDefinition"] = "DestinyDestinationDefinition";
  ManifestComponents["DestinyPlaceDefinition"] = "DestinyPlaceDefinition";
  ManifestComponents["DestinyActivityDefinition"] = "DestinyActivityDefinition";
  ManifestComponents["DestinyActivityTypeDefinition"] = "DestinyActivityTypeDefinition";
  ManifestComponents["DestinyActivityModifierDefinition"] = "DestinyActivityModifierDefinition";
  ManifestComponents["DestinyActivityModeDefinition"] = "DestinyActivityModeDefinition";
  ManifestComponents["DestinyActivityGraphDefinition"] = "DestinyActivityGraphDefinition";
  ManifestComponents["DestinyEquipmentSlotDefinition"] = "DestinyEquipmentSlotDefinition";
  ManifestComponents["DestinyInventoryBucketDefinition"] = "DestinyInventoryBucketDefinition";
  ManifestComponents["DestinySocketTypeDefinition"] = "DestinySocketTypeDefinition";
  ManifestComponents["DestinySocketCategoryDefinition"] = "DestinySocketCategoryDefinition";
  ManifestComponents["DestinyVendorGroupDefinition"] = "DestinyVendorGroupDefinition";
  ManifestComponents["DestinySandboxPerkDefinition"] = "DestinySandboxPerkDefinition";
  ManifestComponents["DestinyDamageTypeDefinition"] = "DestinyDamageTypeDefinition";
  ManifestComponents["DestinyStatDefinition"] = "DestinyStatDefinition";
  ManifestComponents["DestinyRecordDefinition"] = "DestinyRecordDefinition";
  ManifestComponents["DestinyLoreDefinition"] = "DestinyLoreDefinition";
  ManifestComponents["DestinyGenderDefinition"] = "DestinyGenderDefinition";
  ManifestComponents["DestinyTraitDefinition"] = "DestinyTraitDefinition";
  ManifestComponents["DestinyMetricDefinition"] = "DestinyMetricDefinition";
  ManifestComponents["DestinyItemTierTypeDefinition"] = "DestinyItemTierTypeDefinition";
  ManifestComponents["DestinyStatGroupDefinition"] = "DestinyStatGroupDefinition";
  ManifestComponents["DestinySandboxPatternDefinition"] = "DestinySandboxPatternDefinition";
  ManifestComponents["DestinyClassDefinition"] = "DestinyClassDefinition";
  ManifestComponents["DestinyArtifactDefinition"] = "DestinyArtifactDefinition";
  ManifestComponents["DestinyProgressionLevelRequirementDefinition"] = "DestinyProgressionLevelRequirementDefinition";
  ManifestComponents["DestinyPowerCapDefinition"] = "DestinyPowerCapDefinition";
  ManifestComponents["DestinyRewardSourceDefinition"] = "DestinyRewardSourceDefinition";
  ManifestComponents["DestinyEnergyTypeDefinition"] = "DestinyEnergyTypeDefinition";
  ManifestComponents["DestinyPlugSetDefinition"] = "DestinyPlugSetDefinition";
  ManifestComponents["DestinyTalentGridDefinition"] = "DestinyTalentGridDefinition";
  ManifestComponents["DestinyItemCategoryDefinition"] = "DestinyItemCategoryDefinition";
  ManifestComponents["DestinyBreakerTypeDefinition"] = "DestinyBreakerTypeDefinition";
  ManifestComponents["DestinySeasonDefinition"] = "DestinySeasonDefinition";
  ManifestComponents["DestinySeasonPassDefinition"] = "DestinySeasonPassDefinition";
  ManifestComponents["DestinyEventCardDefinition"] = "DestinyEventCardDefinition";
  ManifestComponents["DestinyGuardianRankDefinition"] = "DestinyGuardianRankDefinition";
  ManifestComponents["DestinyChecklistDefinition"] = "DestinyChecklistDefinition";
  ManifestComponents["DestinySocialCommendationNodeDefinition"] = "DestinySocialCommendationNodeDefinition";
  ManifestComponents["DestinySocialCommendationDefinition"] = "DestinySocialCommendationDefinition";
  ManifestComponents["DestinyRaceDefinition"] = "DestinyRaceDefinition";
  ManifestComponents["DestinyLoadoutColorDefinition"] = "DestinyLoadoutColorDefinition";
  ManifestComponents["DestinyLoadoutIconDefinition"] = "DestinyLoadoutIconDefinition";
  ManifestComponents["DestinyLoadoutNameDefinition"] = "DestinyLoadoutNameDefinition";
  ManifestComponents["DestinyMilestoneDefinition"] = "DestinyMilestoneDefinition";
  ManifestComponents["DestinyUnlockDefinition"] = "DestinyUnlockDefinition";
  ManifestComponents["DestinyReportReasonCategoryDefinition"] = "DestinyReportReasonCategoryDefinition";
  ManifestComponents["DestinyMedalTierDefinition"] = "DestinyMedalTierDefinition";
  ManifestComponents["DestinyLoadoutConstantsDefinition"] = "DestinyLoadoutConstantsDefinition";
  ManifestComponents["DestinyGuardianRankConstantsDefinition"] = "DestinyGuardianRankConstantsDefinition";
  return ManifestComponents;
}({});
exports.ManifestComponents = ManifestComponents;
const destinyManifestLanguages = ['de', 'en', 'es', 'es-mx', 'fr', 'it', 'ja', 'ko', 'pl', 'pt-br', 'ru', 'zh-chs', 'zh-cht'];
exports.destinyManifestLanguages = destinyManifestLanguages;