

export var ManifestComponents = {
  DestinyProgressionDefinition: "DestinyProgressionDefinition",
  DestinyInventoryItemDefinition: "DestinyInventoryItemDefinition",
  DestinyCollectibleDefinition: "DestinyCollectibleDefinition",
  DestinyMaterialRequirementSetDefinition: "DestinyMaterialRequirementSetDefinition",
  DestinyPresentationNodeDefinition: "DestinyPresentationNodeDefinition",
  DestinyObjectiveDefinition: "DestinyObjectiveDefinition",
  DestinyLocationDefinition: "DestinyLocationDefinition",
  DestinyVendorDefinition: "DestinyVendorDefinition",
  DestinyFactionDefinition: "DestinyFactionDefinition",
  DestinyDestinationDefinition: "DestinyDestinationDefinition",
  DestinyPlaceDefinition: "DestinyPlaceDefinition",
  DestinyActivityDefinition: "DestinyActivityDefinition",
  DestinyActivityTypeDefinition: "DestinyActivityTypeDefinition",
  DestinyActivityModifierDefinition: "DestinyActivityModifierDefinition",
  DestinyActivityModeDefinition: "DestinyActivityModeDefinition",
  DestinyActivityGraphDefinition: "DestinyActivityGraphDefinition",
  DestinyEquipmentSlotDefinition: "DestinyEquipmentSlotDefinition",
  DestinyInventoryBucketDefinition: "DestinyInventoryBucketDefinition",
  DestinySocketTypeDefinition: "DestinySocketTypeDefinition",
  DestinySocketCategoryDefinition: "DestinySocketCategoryDefinition",
  DestinyVendorGroupDefinition: "DestinyVendorGroupDefinition",
  DestinySandboxPerkDefinition: "DestinySandboxPerkDefinition",
  DestinyDamageTypeDefinition: "DestinyDamageTypeDefinition",
  DestinyStatDefinition: "DestinyStatDefinition",
  DestinyRecordDefinition: "DestinyRecordDefinition",
  DestinyLoreDefinition: "DestinyLoreDefinition",
  DestinyGenderDefinition: "DestinyGenderDefinition",
  DestinyTraitDefinition: "DestinyTraitDefinition",
  DestinyTraitCategoryDefinition: "DestinyTraitCategoryDefinition",
  DestinyMetricDefinition: "DestinyMetricDefinition",
  DestinyItemTierTypeDefinition: "DestinyItemTierTypeDefinition",
  DestinyStatGroupDefinition: "DestinyStatGroupDefinition",
  DestinySandboxPatternDefinition: "DestinySandboxPatternDefinition",
  DestinyClassDefinition: "DestinyClassDefinition",
  DestinyArtifactDefinition: "DestinyArtifactDefinition",
  DestinyProgressionLevelRequirementDefinition: "DestinyProgressionLevelRequirementDefinition",
  DestinyPowerCapDefinition: "DestinyPowerCapDefinition",
  DestinyRewardSourceDefinition: "DestinyRewardSourceDefinition",
  DestinyEnergyTypeDefinition: "DestinyEnergyTypeDefinition",
  DestinyPlugSetDefinition: "DestinyPlugSetDefinition",
  DestinyTalentGridDefinition: "DestinyTalentGridDefinition",
  DestinyItemCategoryDefinition: "DestinyItemCategoryDefinition",
  DestinyBreakerTypeDefinition: "DestinyBreakerTypeDefinition",
  DestinySeasonDefinition: "DestinySeasonDefinition",
  DestinySeasonPassDefinition: "DestinySeasonPassDefinition",
  DestinyEventCardDefinition: "DestinyEventCardDefinition",
  DestinyChecklistDefinition: "DestinyChecklistDefinition",
  DestinyRaceDefinition: "DestinyRaceDefinition",
  DestinyMilestoneDefinition: "DestinyMilestoneDefinition",
  DestinyUnlockDefinition: "DestinyUnlockDefinition",
  DestinyReportReasonCategoryDefinition: "DestinyReportReasonCategoryDefinition",
  DestinyMedalTierDefinition: "DestinyMedalTierDefinition"
};

export const destinyManifestLanguages = ['de', 'en', 'es', 'es-mx', 'fr', 'it', 'ja', 'ko', 'pl', 'pt-br', 'ru', 'zh-chs', 'zh-cht'];