/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyObjectiveDisplayProperties
 * @property {number?} activityHash The activity associated with this objective in the context of this item, if any. Mapped to DestinyActivityDefinition in the manifest.
 * @property {boolean} displayOnItemPreviewScreen If true, the game shows this objective on item preview screens.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyObjectiveDisplayProperties}
*/
class DestinyObjectiveDisplayProperties {
  /** @readonly */
  activityHash;
  /** @readonly */
  displayOnItemPreviewScreen;
}
module.exports = DestinyObjectiveDisplayProperties;
