/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * If the activity is a playlist, this is the definition for a specific entry in
 * the playlist: a single possible combination of Activity and Activity Mode that
 * can be chosen.
 * @type {typeof DestinyActivityPlaylistItemDefinition}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyActivityPlaylistItemDefinition}
*/
module.exports = class DestinyActivityPlaylistItemDefinition {
  /**
   * The hash identifier of the Activity that can be played. Use it to look up the
   * DestinyActivityDefinition. Mapped to DestinyActivityDefinition in the manifest.
   * @readonly
   * @type number
  */
  activityHash;
  /**
   * If this playlist entry had an activity mode directly defined on it, this will be
   * the hash of that mode. Mapped to DestinyActivityModeDefinition in the manifest.
   * @readonly
   * @type number?
  */
  directActivityModeHash;
  /**
   * If the playlist entry had an activity mode directly defined on it, this will be
   * the enum value of that mode.
   * @readonly
   * @type number?
  */
  directActivityModeType;
  /**
   * The hash identifiers for Activity Modes relevant to this entry. Mapped to
   * DestinyActivityModeDefinition in the manifest.
   * @readonly
   * @type number[]
  */
  activityModeHashes;
  /**
   * The activity modes - if any - in enum form. Because we can't seem to escape the
   * enums.
   * @readonly
   * @type DestinyActivityModeType[]
  */
  activityModeTypes;
}
