/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
import { DestinyVendorInteractionRewardSelection } from '../DestinyVendorInteractionRewardSelection';
import { DestinyVendorReplyType } from '../DestinyVendorReplyType';
/**
 * When the interaction is replied to, Reward sites will fire and items potentially
 * selected based on whether the given unlock expression is TRUE.
 *
 * You can potentially choose one from multiple replies when replying to an
 * interaction: this is how you get either/or rewards from vendors.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyVendorInteractionReplyDefinition}
*/
export interface DestinyVendorInteractionReplyDefinition {
    /** The rewards granted upon responding to the vendor. */
    readonly itemRewardsSelection: DestinyVendorInteractionRewardSelection;
    /** The localized text for the reply. */
    readonly reply: string;
    /** An enum indicating the type of reply being made. */
    readonly replyType: DestinyVendorReplyType;
}
