/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * This defines a single Step in a progression (which roughly equates to a level.
 * See DestinyProgressionDefinition for caveats).
 * @type DestinyProgressionStepDefinition
 * @property {string} stepName Very rarely, Progressions will have localized text describing the Level of the progression. This will be that localized text, if it exists. Otherwise, the standard appears to be to simply show the level numerically.
 * @property {DestinyProgressionStepDisplayEffect} displayEffectType This appears to be, when you "level up", whether a visual effect will display and on what entity. See DestinyProgressionStepDisplayEffect for slightly more info.
 * @property {number} progressTotal The total amount of progression points/"experience" you will need to initially reach this step. If this is the last step and the progression is repeating indefinitely (DestinyProgressionDefinition.repeatLastStep), this will also be the progress needed to level it up further by repeating this step again.
 * @property {DestinyItemQuantity[]} rewardItems A listing of items rewarded as a result of reaching this level.
 * @property {string} icon If this progression step has a specific icon related to it, this is the icon to show.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyProgressionStepDefinition}
*/
class DestinyProgressionStepDefinition {
  /** @readonly */
  stepName;
  /** @readonly */
  displayEffectType;
  /** @readonly */
  progressTotal;
  /** @readonly */
  rewardItems;
  /** @readonly */
  icon;
}
module.exports = DestinyProgressionStepDefinition;
