/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @typedef {number | DestinyTalentNodeStepDamageTypes.None | DestinyTalentNodeStepDamageTypes.Kinetic | DestinyTalentNodeStepDamageTypes.Arc | DestinyTalentNodeStepDamageTypes.Solar | DestinyTalentNodeStepDamageTypes.Void | DestinyTalentNodeStepDamageTypes.All}DestinyTalentNodeStepDamageTypes
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyTalentNodeStepDamageTypes}
*/
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 * @type DestinyTalentNodeStepDamageTypes
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyTalentNodeStepDamageTypes}
*/
module.exports = Object.freeze({
  None: 0,
  Kinetic: 1,
  Arc: 2,
  Solar: 4,
  Void: 8,
  All: 15
})
