/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * When the interaction is replied to, Reward sites will fire and items potentially
 * selected based on whether the given unlock expression is TRUE.
 *
 * You can potentially choose one from multiple replies when replying to an
 * interaction: this is how you get either/or rewards from vendors.
 * @type DestinyVendorInteractionReplyDefinition
 * @property {DestinyVendorInteractionRewardSelection} itemRewardsSelection The rewards granted upon responding to the vendor.
 * @property {string} reply The localized text for the reply.
 * @property {DestinyVendorReplyType} replyType An enum indicating the type of reply being made.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyVendorInteractionReplyDefinition}
*/
class DestinyVendorInteractionReplyDefinition {
  /** @readonly */
  itemRewardsSelection;
  /** @readonly */
  reply;
  /** @readonly */
  replyType;
}
module.exports = DestinyVendorInteractionReplyDefinition;
