/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * An intrinsic perk on an item, and the requirements for it to be activated.
 * @type {typeof DestinyItemPerkEntryDefinition}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyItemPerkEntryDefinition}
*/
module.exports = class DestinyItemPerkEntryDefinition {
  /**
   * If this perk is not active, this is the string to show for why it's not
   * providing its benefits.
   * @readonly
   * @type string
  */
  requirementDisplayString;
  /**
   * A hash identifier for the DestinySandboxPerkDefinition being provided on the
   * item. Mapped to DestinySandboxPerkDefinition in the manifest.
   * @readonly
   * @type number
  */
  perkHash;
  /**
   * Indicates whether this perk should be shown, or if it should be shown disabled.
   * @readonly
   * @type ItemPerkVisibility
  */
  perkVisibility;
}
