/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyProgressionRewardItemQuantity
 * @property {number} rewardedAtProgressionLevel 
 * @property {DestinyProgressionRewardItemAcquisitionBehavior} acquisitionBehavior 
 * @property {string} uiDisplayStyle 
 * @property {string[]} claimUnlockDisplayStrings 
 * @property {number} itemHash The hash identifier for the item in question. Use it to look up the item's DestinyInventoryItemDefinition. Mapped to DestinyInventoryItemDefinition in the manifest.
 * @property {string?} itemInstanceId If this quantity is referring to a specific instance of an item, this will have the item's instance ID. Normally, this will be null.
 * @property {number} quantity The amount of the item needed/available depending on the context of where DestinyItemQuantity is being used.
 * @property {boolean} hasConditionalVisibility Indicates that this item quantity may be conditionally shown or hidden, based on various sources of state. For example: server flags, account state, or character progress.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyProgressionRewardItemQuantity}
*/
class DestinyProgressionRewardItemQuantity {
  /** @readonly */
  rewardedAtProgressionLevel;
  /** @readonly */
  acquisitionBehavior;
  /** @readonly */
  uiDisplayStyle;
  /** @readonly */
  claimUnlockDisplayStrings;
  /** @readonly */
  itemHash;
  /** @readonly */
  itemInstanceId;
  /** @readonly */
  quantity;
  /** @readonly */
  hasConditionalVisibility;
}
module.exports = DestinyProgressionRewardItemQuantity;
