/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * Defines a Character Class in Destiny 2. These are types of characters you can
 * play, like Titan, Warlock, and Hunter.
 * @type DestinyClassDefinition
 * @property {DestinyClass} classType In Destiny 1, we added a convenience Enumeration for referring to classes. We've kept it, though mostly for posterity. This is the enum value for this definition's class.
 * @property {DestinyDisplayPropertiesDefinition} displayProperties 
 * @property {Object.key<DestinyGender, string>} genderedClassNames A localized string referring to the singular form of the Class's name when referred to in gendered form. Keyed by the DestinyGender.
 * @property {Object.key<number, string>} genderedClassNamesByGenderHash Mapped to DestinyGenderDefinition in the manifest.
 * @property {number?} mentorVendorHash Mentors don't really mean anything anymore. Don't expect this to be populated. Mapped to DestinyVendorDefinition in the manifest.
 * @property {number} hash The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
When entities refer to each other in Destiny content, it is this hash that they are referring to.
 * @property {number} index The index of the entity as it was found in the investment tables.
 * @property {boolean} redacted If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyClassDefinition}
*/
class DestinyClassDefinition {
  /** @readonly */
  classType;
  /** @readonly */
  displayProperties;
  /** @readonly */
  genderedClassNames;
  /** @readonly */
  genderedClassNamesByGenderHash;
  /** @readonly */
  mentorVendorHash;
  /** @readonly */
  hash;
  /** @readonly */
  index;
  /** @readonly */
  redacted;
}
module.exports = DestinyClassDefinition;
