/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyArtifactTierDefinition
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Artifacts.DestinyArtifactTierDefinition}
*/
class DestinyArtifactTierDefinition {
  /**
   * An identifier, unique within the Artifact, for this specific tier.
   * @readonly
   * @type number
  */
  tierHash;
  /**
   * The human readable title of this tier, if any.
   * @readonly
   * @type string
  */
  displayTitle;
  /**
   * A string representing the localized minimum requirement text for this Tier, if
   * any.
   * @readonly
   * @type string
  */
  progressRequirementMessage;
  /**
   * The items that can be earned within this tier.
   * @readonly
   * @type DestinyArtifactTierItemDefinition[]
  */
  items;
  /**
   * The minimum number of "unlock points" that you must have used before you can
   * unlock items from this tier.
   * @readonly
   * @type number
  */
  minimumUnlockPointsUsedRequirement;
}
module.exports = DestinyArtifactTierDefinition;
