/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * Defines the properties of an 'Event Card' in Destiny 2, to coincide with a
 * seasonal event for additional challenges, premium rewards, a new seal, and a
 * special title. For example: Solstice of Heroes 2022.
 * @type DestinyEventCardDefinition
 * @property {DestinyDisplayPropertiesDefinition} displayProperties 
 * @property {string} linkRedirectPath 
 * @property {DestinyColor} color 
 * @property {DestinyEventCardImages} images 
 * @property {number} triumphsPresentationNodeHash Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {number} sealPresentationNodeHash Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {number} ticketCurrencyItemHash Mapped to DestinyInventoryItemDefinition in the manifest.
 * @property {number} ticketVendorHash Mapped to DestinyVendorDefinition in the manifest.
 * @property {number} ticketVendorCategoryHash 
 * @property {string} endTime 
 * @property {number} hash The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
When entities refer to each other in Destiny content, it is this hash that they are referring to.
 * @property {number} index The index of the entity as it was found in the investment tables.
 * @property {boolean} redacted If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Seasons.DestinyEventCardDefinition}
*/
class DestinyEventCardDefinition {
  /** @readonly */
  displayProperties;
  /** @readonly */
  linkRedirectPath;
  /** @readonly */
  color;
  /** @readonly */
  images;
  /** @readonly */
  triumphsPresentationNodeHash;
  /** @readonly */
  sealPresentationNodeHash;
  /** @readonly */
  ticketCurrencyItemHash;
  /** @readonly */
  ticketVendorHash;
  /** @readonly */
  ticketVendorCategoryHash;
  /** @readonly */
  endTime;
  /** @readonly */
  hash;
  /** @readonly */
  index;
  /** @readonly */
  redacted;
}
module.exports = DestinyEventCardDefinition;
