/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * Defines a canonical "Season" of Destiny: a range of a few months where the game
 * highlights certain challenges, provides new loot, has new Clan-related rewards
 * and celebrates various seasonal events.
 * @type DestinySeasonDefinition
 * @property {DestinyDisplayPropertiesDefinition} displayProperties 
 * @property {string} backgroundImagePath 
 * @property {number} seasonNumber 
 * @property {string?} startDate 
 * @property {string?} endDate 
 * @property {number?} seasonPassHash Mapped to DestinySeasonPassDefinition in the manifest.
 * @property {number?} seasonPassProgressionHash Mapped to DestinyProgressionDefinition in the manifest.
 * @property {number?} artifactItemHash Mapped to DestinyInventoryItemDefinition in the manifest.
 * @property {number?} sealPresentationNodeHash Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {number?} seasonalChallengesPresentationNodeHash Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {DestinySeasonPreviewDefinition} preview Optional - Defines the promotional text, images, and links to preview this season.
 * @property {number} hash The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
When entities refer to each other in Destiny content, it is this hash that they are referring to.
 * @property {number} index The index of the entity as it was found in the investment tables.
 * @property {boolean} redacted If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Seasons.DestinySeasonDefinition}
*/
class DestinySeasonDefinition {
  /** @readonly */
  displayProperties;
  /** @readonly */
  backgroundImagePath;
  /** @readonly */
  seasonNumber;
  /** @readonly */
  startDate;
  /** @readonly */
  endDate;
  /** @readonly */
  seasonPassHash;
  /** @readonly */
  seasonPassProgressionHash;
  /** @readonly */
  artifactItemHash;
  /** @readonly */
  sealPresentationNodeHash;
  /** @readonly */
  seasonalChallengesPresentationNodeHash;
  /** @readonly */
  preview;
  /** @readonly */
  hash;
  /** @readonly */
  index;
  /** @readonly */
  redacted;
}
module.exports = DestinySeasonDefinition;
