/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
/**
 * Defines the thumbnail icon, high-res image, and video link for promotional
 * images
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Seasons.DestinySeasonPreviewImageDefinition}
*/
export interface DestinySeasonPreviewImageDefinition {
    /** A thumbnail icon path to preview seasonal content, probably 480x270. */
    readonly thumbnailImage: string;
    /** An optional path to a high-resolution image, probably 1920x1080. */
    readonly highResImage: string;
}
