/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyEnvironmentLocationMapping}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Constants.DestinyEnvironmentLocationMapping}
*/
module.exports = class DestinyEnvironmentLocationMapping {
  /**
   * The location that is revealed on the director by this mapping. Mapped to
   * DestinyLocationDefinition in the manifest.
   * @readonly
   * @type number
  */
  locationHash;
  /**
   * A hint that the UI uses to figure out how this location is activated by the
   * player.
   * @readonly
   * @type string
  */
  activationSource;
  /**
   * If this is populated, it is the item that you must possess for this location to
   * be active because of this mapping. (theoretically, a location can have multiple
   * mappings, and some might require an item while others don't) Mapped to
   * DestinyInventoryItemDefinition in the manifest.
   * @readonly
   * @type number?
  */
  itemHash;
  /**
   * If this is populated, this is an objective related to the location. Mapped to
   * DestinyObjectiveDefinition in the manifest.
   * @readonly
   * @type number?
  */
  objectiveHash;
  /**
   * If this is populated, this is the activity you have to be playing in order to
   * see this location appear because of this mapping. (theoretically, a location can
   * have multiple mappings, and some might require you to be in a specific activity
   * when others don't) Mapped to DestinyActivityDefinition in the manifest.
   * @readonly
   * @type number?
  */
  activityHash;
}
