"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getGlobalAlerts = exports.getUserSystemOverrides = exports.getCommonSettings = exports.getAvailableLocales = void 0;
var GetAvailableLocales_1 = require("./GetAvailableLocales");
Object.defineProperty(exports, "getAvailableLocales", { enumerable: true, get: function () { return GetAvailableLocales_1.getAvailableLocales; } });
var GetCommonSettings_1 = require("./GetCommonSettings");
Object.defineProperty(exports, "getCommonSettings", { enumerable: true, get: function () { return GetCommonSettings_1.getCommonSettings; } });
var GetUserSystemOverrides_1 = require("./GetUserSystemOverrides");
Object.defineProperty(exports, "getUserSystemOverrides", { enumerable: true, get: function () { return GetUserSystemOverrides_1.getUserSystemOverrides; } });
var GetGlobalAlerts_1 = require("./GetGlobalAlerts");
Object.defineProperty(exports, "getGlobalAlerts", { enumerable: true, get: function () { return GetGlobalAlerts_1.getGlobalAlerts; } });
