"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.3
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
Object.defineProperty(exports, "__esModule", { value: true });
exports.DestinyStatAggregationType = void 0;
/**
 * When a Stat (DestinyStatDefinition) is aggregated, this is the rules used for
 * determining the level and formula used for aggregation.
 *
 * * CharacterAverage = apply a weighted average using the related
 * DestinyStatGroupDefinition on the DestinyInventoryItemDefinition across the
 * character's equipped items. See both of those definitions for details. *
 * Character = don't aggregate: the stat should be located and used directly on the
 * character. * Item = don't aggregate: the stat should be located and used
 * directly on the item.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.DestinyStatAggregationType}
*/
var DestinyStatAggregationType;
(function (DestinyStatAggregationType) {
    DestinyStatAggregationType[DestinyStatAggregationType["CharacterAverage"] = 0] = "CharacterAverage";
    DestinyStatAggregationType[DestinyStatAggregationType["Character"] = 1] = "Character";
    DestinyStatAggregationType[DestinyStatAggregationType["Item"] = 2] = "Item";
})(DestinyStatAggregationType = exports.DestinyStatAggregationType || (exports.DestinyStatAggregationType = {}));
