"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.1
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
Object.defineProperty(exports, "__esModule", { value: true });
exports.DestinySocketVisibility = void 0;
/** @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.DestinySocketVisibility} */
var DestinySocketVisibility;
(function (DestinySocketVisibility) {
    DestinySocketVisibility[DestinySocketVisibility["Visible"] = 0] = "Visible";
    DestinySocketVisibility[DestinySocketVisibility["Hidden"] = 1] = "Hidden";
    DestinySocketVisibility[DestinySocketVisibility["HiddenWhenEmpty"] = 2] = "HiddenWhenEmpty";
    DestinySocketVisibility[DestinySocketVisibility["HiddenIfNoPlugsAvailable"] = 3] = "HiddenIfNoPlugsAvailable";
})(DestinySocketVisibility = exports.DestinySocketVisibility || (exports.DestinySocketVisibility = {}));
