"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.3
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
Object.defineProperty(exports, "__esModule", { value: true });
exports.DestinyVendorInteractionRewardSelection = void 0;
/**
 * When a Vendor Interaction provides rewards, they'll either let you choose one or
 * let you have all of them. This determines which it will be.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.DestinyVendorInteractionRewardSelection}
*/
var DestinyVendorInteractionRewardSelection;
(function (DestinyVendorInteractionRewardSelection) {
    DestinyVendorInteractionRewardSelection[DestinyVendorInteractionRewardSelection["None"] = 0] = "None";
    DestinyVendorInteractionRewardSelection[DestinyVendorInteractionRewardSelection["One"] = 1] = "One";
    DestinyVendorInteractionRewardSelection[DestinyVendorInteractionRewardSelection["All"] = 2] = "All";
})(DestinyVendorInteractionRewardSelection = exports.DestinyVendorInteractionRewardSelection || (exports.DestinyVendorInteractionRewardSelection = {}));
