

export let DestinyComponentType;
(function (DestinyComponentType) {
  DestinyComponentType[DestinyComponentType["None"] = 0] = "None";
  DestinyComponentType[DestinyComponentType["Profiles"] = 100] = "Profiles";
  DestinyComponentType[DestinyComponentType["VendorReceipts"] = 101] = "VendorReceipts";
  DestinyComponentType[DestinyComponentType["ProfileInventories"] = 102] = "ProfileInventories";
  DestinyComponentType[DestinyComponentType["ProfileCurrencies"] = 103] = "ProfileCurrencies";
  DestinyComponentType[DestinyComponentType["ProfileProgression"] = 104] = "ProfileProgression";
  DestinyComponentType[DestinyComponentType["PlatformSilver"] = 105] = "PlatformSilver";
  DestinyComponentType[DestinyComponentType["Characters"] = 200] = "Characters";
  DestinyComponentType[DestinyComponentType["CharacterInventories"] = 201] = "CharacterInventories";
  DestinyComponentType[DestinyComponentType["CharacterProgressions"] = 202] = "CharacterProgressions";
  DestinyComponentType[DestinyComponentType["CharacterRenderData"] = 203] = "CharacterRenderData";
  DestinyComponentType[DestinyComponentType["CharacterActivities"] = 204] = "CharacterActivities";
  DestinyComponentType[DestinyComponentType["CharacterEquipment"] = 205] = "CharacterEquipment";
  DestinyComponentType[DestinyComponentType["ItemInstances"] = 300] = "ItemInstances";
  DestinyComponentType[DestinyComponentType["ItemObjectives"] = 301] = "ItemObjectives";
  DestinyComponentType[DestinyComponentType["ItemPerks"] = 302] = "ItemPerks";
  DestinyComponentType[DestinyComponentType["ItemRenderData"] = 303] = "ItemRenderData";
  DestinyComponentType[DestinyComponentType["ItemStats"] = 304] = "ItemStats";
  DestinyComponentType[DestinyComponentType["ItemSockets"] = 305] = "ItemSockets";
  DestinyComponentType[DestinyComponentType["ItemTalentGrids"] = 306] = "ItemTalentGrids";
  DestinyComponentType[DestinyComponentType["ItemCommonData"] = 307] = "ItemCommonData";
  DestinyComponentType[DestinyComponentType["ItemPlugStates"] = 308] = "ItemPlugStates";
  DestinyComponentType[DestinyComponentType["ItemPlugObjectives"] = 309] = "ItemPlugObjectives";
  DestinyComponentType[DestinyComponentType["ItemReusablePlugs"] = 310] = "ItemReusablePlugs";
  DestinyComponentType[DestinyComponentType["Vendors"] = 400] = "Vendors";
  DestinyComponentType[DestinyComponentType["VendorCategories"] = 401] = "VendorCategories";
  DestinyComponentType[DestinyComponentType["VendorSales"] = 402] = "VendorSales";
  DestinyComponentType[DestinyComponentType["Kiosks"] = 500] = "Kiosks";
  DestinyComponentType[DestinyComponentType["CurrencyLookups"] = 600] = "CurrencyLookups";
  DestinyComponentType[DestinyComponentType["PresentationNodes"] = 700] = "PresentationNodes";
  DestinyComponentType[DestinyComponentType["Collectibles"] = 800] = "Collectibles";
  DestinyComponentType[DestinyComponentType["Records"] = 900] = "Records";
  DestinyComponentType[DestinyComponentType["Transitory"] = 1000] = "Transitory";
  DestinyComponentType[DestinyComponentType["Metrics"] = 1100] = "Metrics";
  DestinyComponentType[DestinyComponentType["StringVariables"] = 1200] = "StringVariables";
  DestinyComponentType[DestinyComponentType["Craftables"] = 1300] = "Craftables";
})(DestinyComponentType || (DestinyComponentType = {}));