/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @typedef {number | DestinyRecordToastStyle.None | DestinyRecordToastStyle.Record | DestinyRecordToastStyle.Lore | DestinyRecordToastStyle.Badge | DestinyRecordToastStyle.MetaRecord | DestinyRecordToastStyle.MedalComplete | DestinyRecordToastStyle.SeasonChallengeComplete | DestinyRecordToastStyle.GildedTitleComplete | DestinyRecordToastStyle.CraftingRecipeUnlocked}DestinyRecordToastStyle
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.DestinyRecordToastStyle}
*/
module.exports = Object.freeze({
  None: 0,
  Record: 1,
  Lore: 2,
  Badge: 3,
  MetaRecord: 4,
  MedalComplete: 5,
  SeasonChallengeComplete: 6,
  GildedTitleComplete: 7,
  CraftingRecipeUnlocked: 8
})
