/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

exports.TrendingEntryType = require('./TrendingEntryType');
exports.TrendingCategories = require('./TrendingCategories');
exports.TrendingCategory = require('./TrendingCategory');
exports.TrendingEntry = require('./TrendingEntry');
exports.TrendingDetail = require('./TrendingDetail');
exports.TrendingEntryNews = require('./TrendingEntryNews');
exports.TrendingEntrySupportArticle = require('./TrendingEntrySupportArticle');
exports.TrendingEntryDestinyItem = require('./TrendingEntryDestinyItem');
exports.TrendingEntryDestinyActivity = require('./TrendingEntryDestinyActivity');
exports.TrendingEntryDestinyRitual = require('./TrendingEntryDestinyRitual');
exports.TrendingEntryCommunityCreation = require('./TrendingEntryCommunityCreation');
