/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof TrendingEntryDestinyRitual}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Trending.TrendingEntryDestinyRitual}
*/
module.exports = class TrendingEntryDestinyRitual {
  /**
   * @readonly
   * @type string
  */
  image;
  /**
   * @readonly
   * @type string
  */
  icon;
  /**
   * @readonly
   * @type string
  */
  title;
  /**
   * @readonly
   * @type string
  */
  subtitle;
  /**
   * @readonly
   * @type string
  */
  dateStart;
  /**
   * @readonly
   * @type string
  */
  dateEnd;
  /**
   * A destiny event does not necessarily have a related Milestone, but if it does
   * the details will be returned here.
   * @readonly
   * @type import('../Destiny/Milestones/DestinyPublicMilestone')
  */
  milestoneDetails;
  /**
   * A destiny event will not necessarily have milestone "custom content", but if it
   * does the details will be here.
   * @readonly
   * @type import('../Destiny/Milestones/DestinyMilestoneContent')
  */
  eventContent;
}
