/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//

import { BungieClientProtocol } from '../../client';
import { BungieNetResponse } from '../../interfaces/BungieNetResponse';
import { RuntimeGroupMemberType } from '../../models';
import { SearchResultOfGroupMember } from '../../models';
/** @see {@link https://bungie-net.github.io/#GroupV2.GetMembersOfGroup} */
export type GetMembersOfGroupParams = {
  /** Page number (starting with 1). Each page has a fixed size of 50 items per page. */
  currentpage: number;
  /** The ID of the group. */
  groupId: string;
  /** Filter out other member types. Use None for all members. */
  memberType?: RuntimeGroupMemberType;
  /**
   * The name fragment upon which a search should be executed for members with
   * matching display or unique names.
   */
  nameSearch?: string;
};

/**
 * Get the list of members in a given group.
 * @see {@link https://bungie-net.github.io/#GroupV2.GetMembersOfGroup}
 */
export async function getMembersOfGroup(
  params: GetMembersOfGroupParams,
  client: BungieClientProtocol
): Promise<BungieNetResponse<SearchResultOfGroupMember>> {
  return client.fetch<SearchResultOfGroupMember>({
    method: 'GET',
    url: `https://www.bungie.net/Platform/GroupV2/${params.groupId}/Members/`,
    params: {
      currentpage: params.currentpage,
      memberType: params.memberType,
      nameSearch: params.nameSearch
    }
  });
}
