/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Do not edit these files manually.
 */
//

/**
 * If progression is earned, this determines whether the progression shows visual
 * effects on the character or its item - or neither.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.DestinyProgressionStepDisplayEffect}
 */
export const enum DestinyProgressionStepDisplayEffect {
  None = 0,
  Character = 1,
  Item = 2
}
