"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getPlatformFriendList = exports.removeFriendRequest = exports.removeFriend = exports.declineFriendRequest = exports.acceptFriendRequest = exports.issueFriendRequest = exports.getFriendRequestList = exports.getFriendList = void 0;
var GetFriendList_1 = require("./GetFriendList");
Object.defineProperty(exports, "getFriendList", { enumerable: true, get: function () { return GetFriendList_1.getFriendList; } });
var GetFriendRequestList_1 = require("./GetFriendRequestList");
Object.defineProperty(exports, "getFriendRequestList", { enumerable: true, get: function () { return GetFriendRequestList_1.getFriendRequestList; } });
var IssueFriendRequest_1 = require("./IssueFriendRequest");
Object.defineProperty(exports, "issueFriendRequest", { enumerable: true, get: function () { return IssueFriendRequest_1.issueFriendRequest; } });
var AcceptFriendRequest_1 = require("./AcceptFriendRequest");
Object.defineProperty(exports, "acceptFriendRequest", { enumerable: true, get: function () { return AcceptFriendRequest_1.acceptFriendRequest; } });
var DeclineFriendRequest_1 = require("./DeclineFriendRequest");
Object.defineProperty(exports, "declineFriendRequest", { enumerable: true, get: function () { return DeclineFriendRequest_1.declineFriendRequest; } });
var RemoveFriend_1 = require("./RemoveFriend");
Object.defineProperty(exports, "removeFriend", { enumerable: true, get: function () { return RemoveFriend_1.removeFriend; } });
var RemoveFriendRequest_1 = require("./RemoveFriendRequest");
Object.defineProperty(exports, "removeFriendRequest", { enumerable: true, get: function () { return RemoveFriendRequest_1.removeFriendRequest; } });
var GetPlatformFriendList_1 = require("./GetPlatformFriendList");
Object.defineProperty(exports, "getPlatformFriendList", { enumerable: true, get: function () { return GetPlatformFriendList_1.getPlatformFriendList; } });
