/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyPostGameCarnageReportTeamEntry
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.HistoricalStats.DestinyPostGameCarnageReportTeamEntry}
*/
class DestinyPostGameCarnageReportTeamEntry {
  /**
   * Integer ID for the team.
   * @readonly
   * @type number
  */
  teamId;
  /**
   * Team's standing relative to other teams.
   * @readonly
   * @type DestinyHistoricalStatsValue
  */
  standing;
  /**
   * Score earned by the team
   * @readonly
   * @type DestinyHistoricalStatsValue
  */
  score;
  /**
   * Alpha or Bravo
   * @readonly
   * @type string
  */
  teamName;
}
module.exports = DestinyPostGameCarnageReportTeamEntry;
