/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyHistoricalStatsPeriodGroup}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.HistoricalStats.DestinyHistoricalStatsPeriodGroup}
*/
module.exports = class DestinyHistoricalStatsPeriodGroup {
  /**
   * Period for the group. If the stat periodType is day, then this will have a
   * specific day. If the type is monthly, then this value will be the first day of
   * the applicable month. This value is not set when the periodType is 'all time'.
   * @readonly
   * @type string
  */
  period;
  /**
   * If the period group is for a specific activity, this property will be set.
   * @readonly
   * @type import('./DestinyHistoricalStatsActivity')
  */
  activityDetails;
  /**
   * Collection of stats for the period.
   * @readonly
   * @type {{[key: string]: DestinyHistoricalStatsValue}}
  */
  values;
}
