/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyPlayer
 * @property {UserInfoCard} destinyUserInfo Details about the player as they are known in game (platform display name, Destiny emblem)
 * @property {string} characterClass Class of the character if applicable and available.
 * @property {number} classHash Mapped to DestinyClassDefinition in the manifest.
 * @property {number} raceHash Mapped to DestinyRaceDefinition in the manifest.
 * @property {number} genderHash Mapped to DestinyGenderDefinition in the manifest.
 * @property {number} characterLevel Level of the character if available. Zero if it is not available.
 * @property {number} lightLevel Light Level of the character if available. Zero if it is not available.
 * @property {UserInfoCard} bungieNetUserInfo Details about the player as they are known on BungieNet. This will be undefined if the player has marked their credential private, or does not have a BungieNet account.
 * @property {string?} clanName Current clan name for the player. This value may be null or an empty string if the user does not have a clan.
 * @property {string?} clanTag Current clan tag for the player. This value may be null or an empty string if the user does not have a clan.
 * @property {number} emblemHash If we know the emblem's hash, this can be used to look up the player's emblem at the time of a match when receiving PGCR data, or otherwise their currently equipped emblem (if we are able to obtain it). Mapped to DestinyInventoryItemDefinition in the manifest.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.HistoricalStats.DestinyPlayer}
*/
class DestinyPlayer {
  /** @readonly */
  destinyUserInfo;
  /** @readonly */
  characterClass;
  /** @readonly */
  classHash;
  /** @readonly */
  raceHash;
  /** @readonly */
  genderHash;
  /** @readonly */
  characterLevel;
  /** @readonly */
  lightLevel;
  /** @readonly */
  bungieNetUserInfo;
  /** @readonly */
  clanName;
  /** @readonly */
  clanTag;
  /** @readonly */
  emblemHash;
}
module.exports = DestinyPlayer;
