/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyLeaderboardEntry}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.HistoricalStats.DestinyLeaderboardEntry}
*/
module.exports = class DestinyLeaderboardEntry {
  /**
   * Where this player ranks on the leaderboard. A value of 1 is the top rank.
   * @readonly
   * @type {number}
  */
  rank;
  /**
   * Identity details of the player
   * @readonly
   * @type {import('./DestinyPlayer')}
  */
  player;
  /**
   * ID of the player's best character for the reported stat.
   * @readonly
   * @type {string}
  */
  characterId;
  /**
   * Value of the stat for this player
   * @readonly
   * @type {import('./DestinyHistoricalStatsValue')}
  */
  value;
}
