/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyHistoricalStatsByPeriod
 * @property {Object.key<string, DestinyHistoricalStatsValue>} allTime 
 * @property {Object.key<string, DestinyHistoricalStatsValue>} allTimeTier1 
 * @property {Object.key<string, DestinyHistoricalStatsValue>} allTimeTier2 
 * @property {Object.key<string, DestinyHistoricalStatsValue>} allTimeTier3 
 * @property {DestinyHistoricalStatsPeriodGroup[]} daily 
 * @property {DestinyHistoricalStatsPeriodGroup[]} monthly 
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.HistoricalStats.DestinyHistoricalStatsByPeriod}
*/
class DestinyHistoricalStatsByPeriod {
  /** @readonly */
  allTime;
  /** @readonly */
  allTimeTier1;
  /** @readonly */
  allTimeTier2;
  /** @readonly */
  allTimeTier3;
  /** @readonly */
  daily;
  /** @readonly */
  monthly;
}
module.exports = DestinyHistoricalStatsByPeriod;
