/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyPresentationNodeComponent}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Components.Presentation.DestinyPresentationNodeComponent}
*/
module.exports = class DestinyPresentationNodeComponent {
  /**
   * This enum represents a set of flags - use bitwise operators to check which of
   * these match your value.
   * @readonly
   * @type DestinyPresentationNodeState
  */
  state;
  /**
   * An optional property: presentation nodes MAY have objectives, which can be used
   * to infer more human readable data about the progress. However, progressValue and
   * completionValue ought to be considered the canonical values for progress on
   * Progression Nodes.
   * @readonly
   * @type DestinyObjectiveProgress
  */
  objective;
  /**
   * How much of the presentation node is considered to be completed so far by the
   * given character/profile.
   * @readonly
   * @type number
  */
  progressValue;
  /**
   * The value at which the presentation node is considered to be completed.
   * @readonly
   * @type number
  */
  completionValue;
  /**
   * If available, this is the current score for the record category that this node
   * represents.
   * @readonly
   * @type number?
  */
  recordCategoryScore;
}
