/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetBungieNetUserByIdParams
 * @property {string} id The requested Bungie.net membership id.
 * @see {@link https://bungie-net.github.io/#User.GetBungieNetUserById}
*/

/**
 * Loads a bungienet user by membership id.
 * @param {GetBungieNetUserByIdParams} params
 * @returns Promise<GeneralUser>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#User.GetBungieNetUserById}
*/
module.exports = async function getBungieNetUserById(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/User/GetBungieNetUserById/${params.id}/`
  });
}
