/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../util/rate-limiter.js');
/**
 * @typedef SearchByGlobalNamePostParams
 * @property {number} page The zero-based page of results you desire.
 * @see {@link https://bungie-net.github.io/#User.SearchByGlobalNamePost}
*/

/**
 * Given the prefix of a global display name, returns all users who share that name.
 * @param {SearchByGlobalNamePostParams} params
 * @returns Promise<import('../../util/server-response.d').BungieNetResponse<UserSearchResponse>>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#User.SearchByGlobalNamePost}
*/
module.exports = async function searchByGlobalNamePost(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'POST',
    url: `https://www.bungie.net/Platform/User/Search/GlobalName/${params.page}/`,
    body
  });
}
