/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyItemInstanceEnergy
 * @property {number} energyTypeHash The type of energy for this item. Plugs that require Energy can only be inserted if they have the "Any" Energy Type or the matching energy type of this item. This is a reference to the DestinyEnergyTypeDefinition for the energy type, where you can find extended info about it. Mapped to DestinyEnergyTypeDefinition in the manifest.
 * @property {DestinyEnergyType} energyType This is the enum version of the Energy Type value, for convenience.
 * @property {number} energyCapacity The total capacity of Energy that the item currently has, regardless of if it is currently being used.
 * @property {number} energyUsed The amount of Energy currently in use by inserted plugs.
 * @property {number} energyUnused The amount of energy still available for inserting new plugs.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Entities.Items.DestinyItemInstanceEnergy}
*/
class DestinyItemInstanceEnergy {
  /** @readonly */
  energyTypeHash;
  /** @readonly */
  energyType;
  /** @readonly */
  energyCapacity;
  /** @readonly */
  energyUsed;
  /** @readonly */
  energyUnused;
}
module.exports = DestinyItemInstanceEnergy;
