/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyItemInstanceEnergy}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Entities.Items.DestinyItemInstanceEnergy}
*/
module.exports = class DestinyItemInstanceEnergy {
  /**
   * The type of energy for this item. Plugs that require Energy can only be inserted
   * if they have the "Any" Energy Type or the matching energy type of this item.
   * This is a reference to the DestinyEnergyTypeDefinition for the energy type,
   * where you can find extended info about it. Mapped to DestinyEnergyTypeDefinition
   * in the manifest.
   * @readonly
   * @type number
  */
  energyTypeHash;
  /**
   * This is the enum version of the Energy Type value, for convenience.
   * @readonly
   * @type DestinyEnergyType
  */
  energyType;
  /**
   * The total capacity of Energy that the item currently has, regardless of if it is
   * currently being used.
   * @readonly
   * @type number
  */
  energyCapacity;
  /**
   * The amount of Energy currently in use by inserted plugs.
   * @readonly
   * @type number
  */
  energyUsed;
  /**
   * The amount of energy still available for inserting new plugs.
   * @readonly
   * @type number
  */
  energyUnused;
}
