/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.4
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//

/** @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Advanced.AwaResponseReason} */
export const enum AwaResponseReason {
  None = 0,
  /** User provided an answer */
  Answered = 1,
  /**
   * The HTTP request timed out, a new request may be made and an answer may still be
   * provided.
   */
  TimedOut = 2,
  /** This request was replaced by another request. */
  Replaced = 3
}
