/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @typedef {number | ForumTopicsSortEnum.Default | ForumTopicsSortEnum.LastReplied | ForumTopicsSortEnum.MostReplied | ForumTopicsSortEnum.Popularity | ForumTopicsSortEnum.Controversiality | ForumTopicsSortEnum.Liked | ForumTopicsSortEnum.HighestRated | ForumTopicsSortEnum.MostUpvoted} ForumTopicsSortEnum
 * @see {@link https://bungie-net.github.io/#/components/schemas/Forum.ForumTopicsSortEnum}
*/
const ForumTopicsSortEnum = Object.freeze({
  Default: 0,
  LastReplied: 1,
  MostReplied: 2,
  Popularity: 3,
  Controversiality: 4,
  Liked: 5,
  HighestRated: 6,
  MostUpvoted: 7
})
module.exports = ForumTopicsSortEnum
