"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.1
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
Object.defineProperty(exports, "__esModule", { value: true });
exports.ForumPostPopularity = void 0;
/** @see {@link https://bungie-net.github.io/#/components/schemas/Forum.ForumPostPopularity} */
var ForumPostPopularity;
(function (ForumPostPopularity) {
    ForumPostPopularity[ForumPostPopularity["Empty"] = 0] = "Empty";
    ForumPostPopularity[ForumPostPopularity["Default"] = 1] = "Default";
    ForumPostPopularity[ForumPostPopularity["Discussed"] = 2] = "Discussed";
    ForumPostPopularity[ForumPostPopularity["CoolStory"] = 3] = "CoolStory";
    ForumPostPopularity[ForumPostPopularity["HeatingUp"] = 4] = "HeatingUp";
    ForumPostPopularity[ForumPostPopularity["Hot"] = 5] = "Hot";
})(ForumPostPopularity = exports.ForumPostPopularity || (exports.ForumPostPopularity = {}));
