/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

/**
 * @type DestinyPresentationNodeChildEntry
 * @property {number} presentationNodeHash Mapped to DestinyPresentationNodeDefinition in the manifest.
 * @property {number} nodeDisplayPriority Use this value to sort the presentation node children in ascending order.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.Presentation.DestinyPresentationNodeChildEntry}
*/
class DestinyPresentationNodeChildEntry {
  /** @readonly */
  presentationNodeHash;
  /** @readonly */
  nodeDisplayPriority;
}
module.exports = DestinyPresentationNodeChildEntry;
