/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//

import { BungieClientProtocol } from '../../client';
import { BungieNetResponse } from '../../interfaces/BungieNetResponse';
import { AwaPermissionRequested } from '../../models';
import { AwaInitializeResponse } from '../../models';
/**
 * Initialize a request to perform an advanced write action.
 * @see {@link https://bungie-net.github.io/#Destiny2.AwaInitializeRequest}
 */
export async function awaInitializeRequest(
  body: AwaPermissionRequested,
  client: BungieClientProtocol
): Promise<BungieNetResponse<AwaInitializeResponse>> {
  return client.fetch<AwaInitializeResponse>({
    method: 'POST',
    url: 'https://www.bungie.net/Platform/Destiny2/Awa/Initialize/',
    body
  });
}
