/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 * 
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 * 
 * OODestiny Version: 2.0.0
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//

import { rateLimitedRequest } from '../../util/rate-limiter.js';
import { BungieNetResponse } from '../../util/server-response.js';
import { InstancedImport, AccessTokenObject } from '../../util/client.js';
import { BungieAPIError } from '../../errors/BungieAPIError.js';
import { AwaPermissionRequested } from '../../schemas/index.js'
import { AwaInitializeResponse } from '../../schemas/index.js'
/**
 * Initialize a request to perform an advanced write action.
 * @see {@link https://bungie-net.github.io/#Destiny2.AwaInitializeRequest}
*/
export async function awaInitializeRequest(this: InstancedImport | AccessTokenObject | void, body: AwaPermissionRequested): Promise<BungieNetResponse<AwaInitializeResponse>> {
const token = (this as InstancedImport)?.client?.access_token as string ?? (this as AccessTokenObject)?.access_token ?? null
  try {
    return await rateLimitedRequest<AwaInitializeResponse>(token, {
      method: 'POST',
      url: 'https://www.bungie.net/Platform/Destiny2/Awa/Initialize/'    ,
      body
    });
  } catch (err) {
    if (err instanceof BungieAPIError) err.stack = new Error().stack
    throw err
  }
}
