/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetContentByIdParams
 * @property {boolean?} head false
 * @property {string} id
 * @property {string} locale
 * @see {@link https://bungie-net.github.io/#Content.GetContentById}
*/

/**
 * Returns a content item referenced by id
 * @param {GetContentByIdParams} params
 * @returns ContentItemPublicContract
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#Content.GetContentById}
*/
module.exports = async function getContentById(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/Content/GetContentById/${params.id}/${params.locale}/`,
    params: {
      head: params.head
    }
  });
}
