/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
import { BungieNetResponse } from '../../util/server-response';
import { InstancedImport, AccessTokenObject } from '../../util/client';
import { NewsArticleRssResponse } from '../../schemas';
/** @see {@link https://bungie-net.github.io/#Content.RssNewsArticles} */
export declare type RssNewsArticlesParams = {
    /** Optionally filter response to only include news items in a certain category. */
    categoryfilter?: string;
    /** Optionally include full content body for each news item. */
    includebody?: boolean;
    /** Zero-based pagination token for paging through result sets. */
    pageToken: string;
};
/**
 * Returns a JSON string response that is the RSS feed for news articles.
 * @see {@link https://bungie-net.github.io/#Content.RssNewsArticles}
 */
export declare function rssNewsArticles(
    this: InstancedImport | AccessTokenObject | void,
    params: RssNewsArticlesParams
): Promise<BungieNetResponse<NewsArticleRssResponse>>;
