/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
import { SingleComponentResponseOfDestinyItemComponent } from '../../SingleComponentResponseOfDestinyItemComponent';
import { SingleComponentResponseOfDestinyItemInstanceComponent } from '../../SingleComponentResponseOfDestinyItemInstanceComponent';
import { SingleComponentResponseOfDestinyItemObjectivesComponent } from '../../SingleComponentResponseOfDestinyItemObjectivesComponent';
import { SingleComponentResponseOfDestinyItemPerksComponent } from '../../SingleComponentResponseOfDestinyItemPerksComponent';
import { SingleComponentResponseOfDestinyItemRenderComponent } from '../../SingleComponentResponseOfDestinyItemRenderComponent';
import { SingleComponentResponseOfDestinyItemStatsComponent } from '../../SingleComponentResponseOfDestinyItemStatsComponent';
import { SingleComponentResponseOfDestinyItemTalentGridComponent } from '../../SingleComponentResponseOfDestinyItemTalentGridComponent';
import { SingleComponentResponseOfDestinyItemSocketsComponent } from '../../SingleComponentResponseOfDestinyItemSocketsComponent';
import { SingleComponentResponseOfDestinyItemReusablePlugsComponent } from '../../SingleComponentResponseOfDestinyItemReusablePlugsComponent';
import { SingleComponentResponseOfDestinyItemPlugObjectivesComponent } from '../../SingleComponentResponseOfDestinyItemPlugObjectivesComponent';
/**
 * The response object for retrieving an individual instanced item. None of these
 * components are relevant for an item that doesn't have an "itemInstanceId": for
 * those, get your information from the DestinyInventoryDefinition.
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Responses.DestinyItemResponse}
*/
export interface DestinyItemResponse {
    /**
     * If the item is on a character, this will return the ID of the character that is
     * holding the item.
    */
    readonly characterId?: string;
    /**
     * Common data for the item relevant to its non-instanced properties.
     *
     * COMPONENT TYPE: ItemCommonData
    */
    readonly item: SingleComponentResponseOfDestinyItemComponent;
    /**
     * Basic instance data for the item.
     *
     * COMPONENT TYPE: ItemInstances
    */
    readonly instance: SingleComponentResponseOfDestinyItemInstanceComponent;
    /**
     * Information specifically about the item's objectives.
     *
     * COMPONENT TYPE: ItemObjectives
    */
    readonly objectives: SingleComponentResponseOfDestinyItemObjectivesComponent;
    /**
     * Information specifically about the perks currently active on the item.
     *
     * COMPONENT TYPE: ItemPerks
    */
    readonly perks: SingleComponentResponseOfDestinyItemPerksComponent;
    /**
     * Information about how to render the item in 3D.
     *
     * COMPONENT TYPE: ItemRenderData
    */
    readonly renderData: SingleComponentResponseOfDestinyItemRenderComponent;
    /**
     * Information about the computed stats of the item: power, defense, etc...
     *
     * COMPONENT TYPE: ItemStats
    */
    readonly stats: SingleComponentResponseOfDestinyItemStatsComponent;
    /**
     * Information about the talent grid attached to the item. Talent nodes can provide
     * a variety of benefits and abilities, and in Destiny 2 are used almost
     * exclusively for the character's "Builds".
     *
     * COMPONENT TYPE: ItemTalentGrids
    */
    readonly talentGrid: SingleComponentResponseOfDestinyItemTalentGridComponent;
    /**
     * Information about the sockets of the item: which are currently active, what
     * potential sockets you could have and the stats/abilities/perks you can gain from
     * them.
     *
     * COMPONENT TYPE: ItemSockets
    */
    readonly sockets: SingleComponentResponseOfDestinyItemSocketsComponent;
    /**
     * Information about the Reusable Plugs for sockets on an item. These are plugs
     * that you can insert into the given socket regardless of if you actually own an
     * instance of that plug: they are logic-driven plugs rather than inventory-driven.
     *
     * These may need to be combined with Plug Set component data to get a full
     * picture of available plugs on a given socket.
     *
     * COMPONENT TYPE: ItemReusablePlugs
    */
    readonly reusablePlugs: SingleComponentResponseOfDestinyItemReusablePlugsComponent;
    /**
     * Information about objectives on Plugs for a given item. See the component's
     * documentation for more info.
     *
     * COMPONENT TYPE: ItemPlugObjectives
    */
    readonly plugObjectives: SingleComponentResponseOfDestinyItemPlugObjectivesComponent;
}
