/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * Raw data about the customization options chosen for a character's face and
 * appearance.
 *
 * You can look up the relevant class/race/gender combo in
 * DestinyCharacterCustomizationOptionDefinition for the character, and then look
 * up these values within the CustomizationOptions found to pull some data about
 * their choices. Warning: not all of that data is meaningful. Some data has useful
 * icons. Others have nothing, and are only meant for 3D rendering purposes (which
 * we sadly do not expose yet)
 * @type {typeof DestinyCharacterCustomization}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Character.DestinyCharacterCustomization}
*/
module.exports = class DestinyCharacterCustomization {
  /**
   * @readonly
   * @type {number}
  */
  personality;
  /**
   * @readonly
   * @type {number}
  */
  face;
  /**
   * @readonly
   * @type {number}
  */
  skinColor;
  /**
   * @readonly
   * @type {number}
  */
  lipColor;
  /**
   * @readonly
   * @type {number}
  */
  eyeColor;
  /**
   * @readonly
   * @type {number[]}
  */
  hairColors;
  /**
   * @readonly
   * @type {number[]}
  */
  featureColors;
  /**
   * @readonly
   * @type {number}
  */
  decalColor;
  /**
   * @readonly
   * @type {boolean}
  */
  wearHelmet;
  /**
   * @readonly
   * @type {number}
  */
  hairIndex;
  /**
   * @readonly
   * @type {number}
  */
  featureIndex;
  /**
   * @readonly
   * @type {number}
  */
  decalIndex;
}
