/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyItemComponentSetOfint64}
 * @see {@link https://bungie-net.github.io/#/components/schemas/DestinyItemComponentSetOfint64}
*/
module.exports = class DestinyItemComponentSetOfint64 {
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent')
  */
  instances;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemRenderComponent')
  */
  renderData;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemStatsComponent')
  */
  stats;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent')
  */
  sockets;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent')
  */
  reusablePlugs;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent')
  */
  plugObjectives;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent')
  */
  talentGrids;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent')
  */
  plugStates;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent')
  */
  objectives;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfint64AndDestinyItemPerksComponent')
  */
  perks;
}
