/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof DestinyItemComponentSetOfuint32}
 * @see {@link https://bungie-net.github.io/#/components/schemas/DestinyItemComponentSetOfuint32}
*/
module.exports = class DestinyItemComponentSetOfuint32 {
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemInstanceComponent')
  */
  instances;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemRenderComponent')
  */
  renderData;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemStatsComponent')
  */
  stats;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemSocketsComponent')
  */
  sockets;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemReusablePlugsComponent')
  */
  reusablePlugs;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemPlugObjectivesComponent')
  */
  plugObjectives;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemTalentGridComponent')
  */
  talentGrids;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent')
  */
  plugStates;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent')
  */
  objectives;
  /**
   * @readonly
   * @type import('./DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent')
  */
  perks;
}
