/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.0
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
/** @see {@link https://bungie-net.github.io/#/components/schemas/Applications.ApplicationStatus} */
export var ApplicationStatus;
(function (ApplicationStatus) {
    /** No value assigned */
    ApplicationStatus[ApplicationStatus["None"] = 0] = "None";
    /**
     * Application exists and works but will not appear in any public catalog. New
     * applications start in this state, test applications will remain in this state.
    */
    ApplicationStatus[ApplicationStatus["Private"] = 1] = "Private";
    /** Active applications that can appear in an catalog. */
    ApplicationStatus[ApplicationStatus["Public"] = 2] = "Public";
    /**
     * Application disabled by the owner. All authorizations will be treated as
     * terminated while in this state. Owner can move back to private or public state.
    */
    ApplicationStatus[ApplicationStatus["Disabled"] = 3] = "Disabled";
    /**
     * Application has been blocked by Bungie. It cannot be transitioned out of this
     * state by the owner. Authorizations are terminated when an application is in this
     * state.
    */
    ApplicationStatus[ApplicationStatus["Blocked"] = 4] = "Blocked";
})(ApplicationStatus || (ApplicationStatus = {}));
