/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-net-core code generator program
 * Repository: {@link https://github.com/owensimpson/bungie-net-core}
 * Do not edit these files manually.
 */
//

import { DestinyDisplayPropertiesDefinition } from '../Common/DestinyDisplayPropertiesDefinition';
import { FireteamFinderCodeOptionType } from '../../FireteamFinderCodeOptionType';
import { FireteamFinderOptionAvailability } from '../../FireteamFinderOptionAvailability';
import { FireteamFinderOptionVisibility } from '../../FireteamFinderOptionVisibility';
import { DestinyFireteamFinderOptionCreatorSettings } from './DestinyFireteamFinderOptionCreatorSettings';
import { DestinyFireteamFinderOptionSearcherSettings } from './DestinyFireteamFinderOptionSearcherSettings';
import { DestinyFireteamFinderOptionValues } from './DestinyFireteamFinderOptionValues';

/** @see {@link https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.FireteamFinder.DestinyFireteamFinderOptionDefinition} */

export interface DestinyFireteamFinderOptionDefinition {
  readonly displayProperties: DestinyDisplayPropertiesDefinition;
  readonly descendingSortPriority: number;
  /** Mapped to DestinyFireteamFinderOptionGroupDefinition in the manifest. */
  readonly groupHash: number;
  readonly codeOptionType: FireteamFinderCodeOptionType;
  /**
   * This enum represents a set of flags - use bitwise operators to check which of
   * these match your value.
   */
  readonly availability: FireteamFinderOptionAvailability;
  readonly visibility: FireteamFinderOptionVisibility;
  readonly uiDisplayStyle: string;
  readonly creatorSettings: DestinyFireteamFinderOptionCreatorSettings;
  readonly searcherSettings: DestinyFireteamFinderOptionSearcherSettings;
  readonly values: DestinyFireteamFinderOptionValues;
  /**
   * The unique identifier for this entity. Guaranteed to be unique for the type of
   * entity, but not globally.
   *
   * When entities refer to each other in Destiny content, it is this hash that they
   * are referring to.
   */
  readonly hash: number;
  /** The index of the entity as it was found in the investment tables. */
  readonly index: number;
  /**
   * If this is true, then there is an entity with this identifier/type combination,
   * but BNet is not yet allowed to show it. Sorry!
   */
  readonly redacted: boolean;
}
