/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

/**
 * @type {typeof FireteamSummary}
 * @see {@link https://bungie-net.github.io/#/components/schemas/Fireteam.FireteamSummary}
*/
module.exports = class FireteamSummary {
  /**
   * @readonly
   * @type string
  */
  fireteamId;
  /**
   * @readonly
   * @type string
  */
  groupId;
  /**
   * @readonly
   * @type FireteamPlatform
  */
  platform;
  /**
   * @readonly
   * @type number
  */
  activityType;
  /**
   * @readonly
   * @type boolean
  */
  isImmediate;
  /**
   * @readonly
   * @type string?
  */
  scheduledTime;
  /**
   * @readonly
   * @type string
  */
  ownerMembershipId;
  /**
   * @readonly
   * @type number
  */
  playerSlotCount;
  /**
   * @readonly
   * @type number?
  */
  alternateSlotCount;
  /**
   * @readonly
   * @type number
  */
  availablePlayerSlotCount;
  /**
   * @readonly
   * @type number
  */
  availableAlternateSlotCount;
  /**
   * @readonly
   * @type string
  */
  title;
  /**
   * @readonly
   * @type string
  */
  dateCreated;
  /**
   * @readonly
   * @type string?
  */
  dateModified;
  /**
   * @readonly
   * @type boolean
  */
  isPublic;
  /**
   * @readonly
   * @type string
  */
  locale;
  /**
   * @readonly
   * @type boolean
  */
  isValid;
  /**
   * @readonly
   * @type string
  */
  datePlayerModified;
  /**
   * @readonly
   * @type string
  */
  titleBeforeModeration;
}
