"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.18.0
 * Contact: support@bungie.com
 *
 * OODestiny Version: 2.0.0
 * NOTE: This class is auto generated by the oodestiny code generator program
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Do not edit these files manually.
 */
//
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Core = exports.Social = exports.Fireteam = exports.Trending = exports.CommunityContent = exports.Destiny2 = exports.Tokens = exports.GroupV2 = exports.Forum = exports.Content = exports.User = exports.App = void 0;
exports.App = __importStar(require("./App/index.js"));
exports.User = __importStar(require("./User/index.js"));
exports.Content = __importStar(require("./Content/index.js"));
exports.Forum = __importStar(require("./Forum/index.js"));
exports.GroupV2 = __importStar(require("./GroupV2/index.js"));
exports.Tokens = __importStar(require("./Tokens/index.js"));
exports.Destiny2 = __importStar(require("./Destiny2/index.js"));
exports.CommunityContent = __importStar(require("./CommunityContent/index.js"));
exports.Trending = __importStar(require("./Trending/index.js"));
exports.Fireteam = __importStar(require("./Fireteam/index.js"));
exports.Social = __importStar(require("./Social/index.js"));
exports.Core = __importStar(require("./Core/index.js"));
