/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-typedef code generator program,
 * adapted from {@link https://github.com/DestinyItemManager/bungie-api-ts}
 * Repository: {@link https://github.com/owensimpson/oodestiny}
 * Do not edit these files manually.
 */
//

const { rateLimitedRequest } = require('../../rate-limiter.js');
/**
 * @typedef GetPostsThreadedPagedFromChildParams
 * @property {string} childPostId
 * @property {number} page
 * @property {number} pageSize
 * @property {number} replySize
 * @property {boolean} rootThreadMode
 * @property {string?} showbanned If this value is not null or empty, banned posts are requested to be returned
 * @property {ForumPostSortEnum} sortMode
 * @see {@link https://bungie-net.github.io/#Forum.GetPostsThreadedPagedFromChild}
*/

/**
 * Returns a thread of posts starting at the topicId of the input childPostId,
 * optionally returning replies to those posts as well as the original parent.
 * @param {GetPostsThreadedPagedFromChildParams} params
 * @returns Promise<PostSearchResponse>
 * @this import(../../index).Client
 * @see {@link https://bungie-net.github.io/#Forum.GetPostsThreadedPagedFromChild}
*/
module.exports = async function getPostsThreadedPagedFromChild(params) {
  return rateLimitedRequest(this.access_token, {
    method: 'GET',
    url: `https://www.bungie.net/Platform/Forum/GetPostsThreadedPagedFromChild/${params.childPostId}/${params.page}/${params.pageSize}/${params.replySize}/${params.rootThreadMode}/${params.sortMode}/`,
    params: {
      showbanned: params.showbanned
    }
  });
}
