"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getRecruitmentThreadSummaries = exports.getPoll = exports.getForumTagSuggestions = exports.getTopicForContent = exports.getPostAndParentAwaitingApproval = exports.getPostAndParent = exports.getPostsThreadedPagedFromChild = exports.getPostsThreadedPaged = exports.getCoreTopicsPaged = exports.getTopicsPaged = void 0;
var GetTopicsPaged_1 = require("./GetTopicsPaged");
Object.defineProperty(exports, "getTopicsPaged", { enumerable: true, get: function () { return GetTopicsPaged_1.getTopicsPaged; } });
var GetCoreTopicsPaged_1 = require("./GetCoreTopicsPaged");
Object.defineProperty(exports, "getCoreTopicsPaged", { enumerable: true, get: function () { return GetCoreTopicsPaged_1.getCoreTopicsPaged; } });
var GetPostsThreadedPaged_1 = require("./GetPostsThreadedPaged");
Object.defineProperty(exports, "getPostsThreadedPaged", { enumerable: true, get: function () { return GetPostsThreadedPaged_1.getPostsThreadedPaged; } });
var GetPostsThreadedPagedFromChild_1 = require("./GetPostsThreadedPagedFromChild");
Object.defineProperty(exports, "getPostsThreadedPagedFromChild", { enumerable: true, get: function () { return GetPostsThreadedPagedFromChild_1.getPostsThreadedPagedFromChild; } });
var GetPostAndParent_1 = require("./GetPostAndParent");
Object.defineProperty(exports, "getPostAndParent", { enumerable: true, get: function () { return GetPostAndParent_1.getPostAndParent; } });
var GetPostAndParentAwaitingApproval_1 = require("./GetPostAndParentAwaitingApproval");
Object.defineProperty(exports, "getPostAndParentAwaitingApproval", { enumerable: true, get: function () { return GetPostAndParentAwaitingApproval_1.getPostAndParentAwaitingApproval; } });
var GetTopicForContent_1 = require("./GetTopicForContent");
Object.defineProperty(exports, "getTopicForContent", { enumerable: true, get: function () { return GetTopicForContent_1.getTopicForContent; } });
var GetForumTagSuggestions_1 = require("./GetForumTagSuggestions");
Object.defineProperty(exports, "getForumTagSuggestions", { enumerable: true, get: function () { return GetForumTagSuggestions_1.getForumTagSuggestions; } });
var GetPoll_1 = require("./GetPoll");
Object.defineProperty(exports, "getPoll", { enumerable: true, get: function () { return GetPoll_1.getPoll; } });
var GetRecruitmentThreadSummaries_1 = require("./GetRecruitmentThreadSummaries");
Object.defineProperty(exports, "getRecruitmentThreadSummaries", { enumerable: true, get: function () { return GetRecruitmentThreadSummaries_1.getRecruitmentThreadSummaries; } });
